/**
 * Script upload scenarii RAG în Firestore.
 * Apelează uploadAllScenarii() dintr-un buton dev în ProfileScreen.
 * Structura: /rag_knowledge/{categorie}/scenarii/{id}
 */
import { doc, setDoc } from 'firebase/firestore';
import { db } from '../firebase/config';
import { Scenariu } from '../services/rag';

// ─── Date ─────────────────────────────────────────────────────────────────────

const SCENARII: Scenariu[] = [

  // ── SANITARE (san_001 – san_015) ───────────────────────────────────────────

  { id: 'san_001', categorie: 'sanitare', titlu: 'Robinet bucătărie care picură', problema: 'Robinetul de la bucătărie picură continuu chiar și când este închis complet.', cuvinte_cheie: ['robinet', 'picura', 'bucatarie', 'garnitura', 'cartus', 'ceramic'], solutie_rezumat: 'Înlocuiește garnitura de cauciuc sau cartușul ceramic din interiorul robinetului.', dificultate: 'Ușor', timp_estimat: '30-45 min', materiale: ['Garnitură robinet', 'Unsoare silicon', 'Cheie reglabilă'], cand_specialist: 'Dacă după înlocuire tot picură sau dacă robinetul e vechi de peste 15 ani.' },

  { id: 'san_002', categorie: 'sanitare', titlu: 'WC care curge continuu în rezervor', problema: 'Se aude zgomot continuu de apă în vasul de toaletă, rezervorul nu se oprește.', cuvinte_cheie: ['wc', 'toaleta', 'rezervor', 'curge', 'zgomot', 'apa', 'plutitor', 'supapa'], solutie_rezumat: 'Reglează sau înlocuiește supapa de umplere (plutitorul) din rezervor.', dificultate: 'Ușor', timp_estimat: '20-30 min', materiale: ['Supapă plutitor universală', 'Garnitură cauciuc'], cand_specialist: 'Dacă rezervorul are fisuri sau supapa nouă tot nu etanșează.' },

  { id: 'san_003', categorie: 'sanitare', titlu: 'Țeavă care curge sub chiuvetă', problema: 'Se observă picături sau baltă de apă sub chiuvetă, venind de la îmbinările țevilor.', cuvinte_cheie: ['teava', 'chiuveta', 'curge', 'scurgere', 'sifon', 'imbinare', 'etansare'], solutie_rezumat: 'Strânge piulițele de la sifon sau înlocuiește garniturile de etanșare.', dificultate: 'Ușor', timp_estimat: '15-30 min', materiale: ['Garnituri sifon', 'Teflon', 'Cheie pentru țevi'], cand_specialist: 'Dacă țeava e crăpată sau corodată — necesită înlocuire.' },

  { id: 'san_004', categorie: 'sanitare', titlu: 'Presiune slabă la apă', problema: 'Apa curge slab la robinete, presiunea este mult mai mică decât normal.', cuvinte_cheie: ['presiune', 'apa', 'slab', 'robinet', 'filtru', 'calcar', 'aerator'], solutie_rezumat: 'Curăță sau înlocuiește aeratorul de la robinet. Verifică filtrul de sedimente de pe conducta principală.', dificultate: 'Ușor', timp_estimat: '20-40 min', materiale: ['Aerator de robinet', 'Soluție detartrant', 'Cheie reglabilă'], cand_specialist: 'Dacă presiunea e slabă în toată casa — posibil problemă la contorul de apă sau rețeaua stradală.' },

  { id: 'san_005', categorie: 'sanitare', titlu: 'Apă caldă nu vine sau vine rece', problema: 'Nu există apă caldă sau vine apă caldă după mult timp de așteptare.', cuvinte_cheie: ['apa', 'calda', 'boiler', 'termostat', 'rezistenta', 'incalzire', 'electric'], solutie_rezumat: 'Verifică dacă boilerul e pornit, termostat setat corect. Rezistența electrică poate fi arsă.', dificultate: 'Mediu', timp_estimat: '1-2 ore', materiale: ['Rezistență boiler', 'Termostat boiler', 'Garnitură'], cand_specialist: 'Dacă boilerul are peste 10 ani sau dacă e problemă de instalație electrică.' },

  { id: 'san_006', categorie: 'sanitare', titlu: 'Sifon chiuvetă înfundat', problema: 'Apa se scurge foarte lent sau deloc din chiuvetă sau cadă de baie.', cuvinte_cheie: ['sifon', 'infundat', 'scurgere', 'lent', 'chiuveta', 'cada', 'par', 'grasime'], solutie_rezumat: 'Demontează și curăță sifonul. Folosește desfundator cu ventuza sau soluție chimică de desfundat.', dificultate: 'Ușor', timp_estimat: '20-30 min', materiale: ['Desfundator ventuza', 'Soluție desfundat', 'Mănuși'], cand_specialist: 'Dacă înfundarea e mai adâncă în coloana de scurgere.' },

  { id: 'san_007', categorie: 'sanitare', titlu: 'Cabina de duș curge la baza', problema: 'Apa iese pe sub cabina de duș sau pe lângă perdelă pe parchetul sau gresie din baie.', cuvinte_cheie: ['dus', 'cabina', 'curge', 'scurgere', 'silicon', 'etansare', 'garnitura'], solutie_rezumat: 'Reaplică silicon sanitar pe toată baza cabinei. Verifică etanșarea ușii de la cabină.', dificultate: 'Ușor', timp_estimat: '1-2 ore + uscare 24h', materiale: ['Silicon sanitar', 'Pistol silicon', 'Alcool izopropilic'], cand_specialist: 'Dacă placa de duș are fisuri sau dacă gresia e afectată de umezeală.' },

  { id: 'san_008', categorie: 'sanitare', titlu: 'Baterie monocomandă defectă — apă nu se oprește', problema: 'Bateria cu mâner unic nu oprește complet apa sau curge pe lângă mâner.', cuvinte_cheie: ['baterie', 'monocomanda', 'maneta', 'cartus', 'ceramic', 'picura', 'scurgere'], solutie_rezumat: 'Înlocuiește cartușul ceramic din interiorul bateriei — are de obicei 35mm sau 40mm diametru.', dificultate: 'Mediu', timp_estimat: '45-60 min', materiale: ['Cartuș ceramic 35/40mm', 'Unsoare silicon', 'Cheie hex'], cand_specialist: 'Dacă bateria e veche și piesele nu mai sunt disponibile — mai economic să schimbi toată bateria.' },

  { id: 'san_009', categorie: 'sanitare', titlu: 'Rezervor WC nu se umple sau se umple lent', problema: 'După tragere, rezervorul toaletei se umple foarte lent sau nu se umple deloc.', cuvinte_cheie: ['rezervor', 'wc', 'toaleta', 'umplere', 'lent', 'supapa', 'filtru', 'calcar'], solutie_rezumat: 'Curăță filtrul de sedimente de la intrarea apei în rezervor. Verifică supapa de umplere.', dificultate: 'Ușor', timp_estimat: '20-30 min', materiale: ['Supapă umplere', 'Garnituri', 'Soluție detartrant'], cand_specialist: 'Dacă presiunea în apartament e în general slabă.' },

  { id: 'san_010', categorie: 'sanitare', titlu: 'Miros neplăcut din canalizare', problema: 'Se simte miros de canalizare în baie sau bucătărie, mai ales dimineața.', cuvinte_cheie: ['miros', 'canalizare', 'sifon', 'uscat', 'gaz', 'baie', 'bucatarie'], solutie_rezumat: 'Toarnă apă în sifonele rar folosite. Verifică garnitura de la baza vasului WC. Curăță sifoanele.', dificultate: 'Ușor', timp_estimat: '15-30 min', materiale: ['Soluție curățare canalizare', 'Silicon sanitar'], cand_specialist: 'Dacă mirosul persiste după curățare — posibil problemă la coloana de ventilație.' },

  { id: 'san_011', categorie: 'sanitare', titlu: 'Robinet termostatat nu reglează temperatura', problema: 'Robinetul cu termostat nu menține temperatura setată sau apa iese mereu rece/fierbinte.', cuvinte_cheie: ['termostat', 'robinet', 'temperatura', 'reglare', 'cartus', 'termostatat'], solutie_rezumat: 'Calibrează sau înlocuiește cartușul termostatic. Verifică limitatorul de temperatură.', dificultate: 'Mediu', timp_estimat: '45-90 min', materiale: ['Cartuș termostatic', 'Unsoare silicon'], cand_specialist: 'Dacă marca nu mai are piese de schimb disponibile.' },

  { id: 'san_012', categorie: 'sanitare', titlu: 'Boiler electric face zgomot (clocotit, pocnit)', problema: 'Boilerul face zgomote puternice de clocotit sau pocnit în timpul încălzirii.', cuvinte_cheie: ['boiler', 'zgomot', 'calcar', 'rezistenta', 'clocotit', 'pocnit', 'detartrat'], solutie_rezumat: 'Detartrează rezistența sau înlocuiește-o. Golește și curăță boilerul anual.', dificultate: 'Mediu', timp_estimat: '2-3 ore', materiale: ['Soluție detartrant', 'Rezistență boiler', 'Garnitură'], cand_specialist: 'Dacă boilerul are peste 8 ani și rezistența e puternic corodată.' },

  { id: 'san_013', categorie: 'sanitare', titlu: 'Calcar pe capul de duș — jet slab', problema: 'Jetul de la dușul de mână e slab sau iese în direcții greșite din cauza calcarului.', cuvinte_cheie: ['dus', 'cap', 'calcar', 'jet', 'slab', 'detartrant', 'orificit'], solutie_rezumat: 'Înmoaie capul de duș în oțet alb 2-3 ore sau soluție detartrant diluată.', dificultate: 'Foarte ușor', timp_estimat: '5 min + 3 ore înmuiat', materiale: ['Oțet alb', 'Punguță plastic', 'Elastic'], cand_specialist: 'Nu este necesar — operațiune de întreținere simplă.' },

  { id: 'san_014', categorie: 'sanitare', titlu: 'Țeavă înghețată iarna', problema: 'Apa nu mai curge iarna la robinet, posibil țeavă înghețată.', cuvinte_cheie: ['teava', 'inghetata', 'iarna', 'frig', 'dezghetat', 'apa', 'inghet'], solutie_rezumat: 'Dezgheață lent cu foen sau prosoape calde. NU folosești flacără. Izolează țeava pentru viitor.', dificultate: 'Mediu', timp_estimat: '30-120 min', materiale: ['Foen', 'Prosoape calde', 'Spumă izolație țevi'], cand_specialist: 'Dacă țeava s-a spart din cauza înghețului — intervenție urgentă necesară.' },

  { id: 'san_015', categorie: 'sanitare', titlu: 'Robinetul de închidere principal nu funcționează', problema: 'Robinetul general de apă al apartamentului este blocat sau nu închide complet.', cuvinte_cheie: ['robinet', 'inchidere', 'principal', 'general', 'blocat', 'vana', 'apart'], solutie_rezumat: 'Lubrifică cu WD-40 și mișcă treptat. Dacă e corodat, înlocuiește cu o vană sferică nouă.', dificultate: 'Mediu', timp_estimat: '1-2 ore', materiale: ['WD-40', 'Vană sferică 1/2"', 'Teflon', 'Cheie reglabilă'], cand_specialist: 'Întotdeauna — necesită închiderea apei pe coloana blocului.' },

  // ── ELECTRIC (el_001 – el_015) ─────────────────────────────────────────────

  { id: 'el_001', categorie: 'electric', titlu: 'Siguranțe automate care sar frecvent', problema: 'Siguranța automată dintr-un circuit sare frecvent, mai ales când pornești aparate.', cuvinte_cheie: ['siguranta', 'automata', 'sare', 'circuit', 'suprasarcina', 'tablou', 'disjunctor'], solutie_rezumat: 'Identifică aparatele care consumă mult pe același circuit. Nu supraîncărca prizele. Verifică dacă siguranța e dimensionată corect.', dificultate: 'Mediu', timp_estimat: '30-60 min', materiale: ['Siguranță automată calibrată corect'], cand_specialist: 'Întotdeauna pentru înlocuire siguranță — risc electrocutare.' },

  { id: 'el_002', categorie: 'electric', titlu: 'Priză care nu funcționează', problema: 'O priză din casă nu alimentează aparatele conectate la ea.', cuvinte_cheie: ['priza', 'functioneaza', 'curent', 'contact', 'faze', 'multimetru', 'nul'], solutie_rezumat: 'Verifică siguranța circuitului la tablou. Verifică dacă prizele sunt pe același circuit cu o priză funcțională.', dificultate: 'Ușor-Mediu', timp_estimat: '15-45 min', materiale: ['Tester priză', 'Înlocuitor priză', 'Șurubelnițe'], cand_specialist: 'Pentru orice intervenție în doze sau tablou electric.' },

  { id: 'el_003', categorie: 'electric', titlu: 'Bec sau lumină care pâlpâie', problema: 'Becul pâlpâie constant sau intermitent, fie el LED sau clasic.', cuvinte_cheie: ['bec', 'palpaie', 'led', 'lumina', 'intrerupator', 'contact', 'driver', 'condensator'], solutie_rezumat: 'La LED: posibil driver defect sau incompatibil cu dimmerul. La incandescent: contact slab la dulie.', dificultate: 'Ușor', timp_estimat: '15-30 min', materiale: ['Bec LED calitate superioară', 'Dulie înlocuire'], cand_specialist: 'Dacă pâlpâie în toată casa — problemă de tensiune sau tablou.' },

  { id: 'el_004', categorie: 'electric', titlu: 'Întrerupător defect sau blocat', problema: 'Întrerupătorul de lumină nu mai face contact, e blocat sau spartat.', cuvinte_cheie: ['intrerupator', 'defect', 'blocat', 'contact', 'lumina', 'inlocuire', 'mecanism'], solutie_rezumat: 'Înlocuiește mecanismul interior al întrerupătorului sau întregul aparat.', dificultate: 'Mediu', timp_estimat: '20-30 min', materiale: ['Întrerupător înlocuitor', 'Șurubelnițe izolate'], cand_specialist: 'Oprește întotdeauna curentul de la tablou înainte de intervenție.' },

  { id: 'el_005', categorie: 'electric', titlu: 'Priză cu scântei sau miros de ars', problema: 'La introducerea ștecherului apar scântei sau se simte miros de plastic ars.', cuvinte_cheie: ['priza', 'scantei', 'miros', 'ars', 'pericol', 'incendiu', 'contact', 'oxid'], solutie_rezumat: 'PERICOL — deconectează imediat și nu mai folosi priza. Necesită înlocuire urgentă.', dificultate: 'URGENT', timp_estimat: 'Imediat', materiale: ['Priză înlocuitor'], cand_specialist: 'OBLIGATORIU — risc de incendiu și electrocutare.' },

  { id: 'el_006', categorie: 'electric', titlu: 'Cablu electric dezizolat sau deteriorat', problema: 'Se observă izolație ruptă, crăpată sau roasă pe un cablu electric din casă.', cuvinte_cheie: ['cablu', 'dezizolat', 'deteriorat', 'izolatie', 'rupt', 'pericol', 'banda'], solutie_rezumat: 'Bandă electroizolantă ca soluție temporară. Înlocuiește cablul imediat.', dificultate: 'URGENT', timp_estimat: 'Imediat + înlocuire 1-4 ore', materiale: ['Bandă electroizolantă', 'Cablu înlocuitor', 'Cleme cablu'], cand_specialist: 'OBLIGATORIU dacă e în pereți sau tablou electric.' },

  { id: 'el_007', categorie: 'electric', titlu: 'Tablou electric vechi cu siguranțe fuzibile', problema: 'Tabloul are siguranțe cu filet vechi, nu disjunctoare automate moderne.', cuvinte_cheie: ['tablou', 'sigurante', 'fuzibile', 'vechi', 'inlocuire', 'modernizare', 'disjunctor'], solutie_rezumat: 'Înlocuirea tabloului electric cu unul modern e obligatorie pentru siguranță. Nu este o operație DIY.', dificultate: 'Avansat', timp_estimat: '4-8 ore', materiale: ['Tablou electric nou', 'Disjunctoare', 'Diferențial'], cand_specialist: 'OBLIGATORIU — electrician autorizat.' },

  { id: 'el_008', categorie: 'electric', titlu: 'Lumina pâlpâie în toată casa', problema: 'Toate luminile din casă pâlpâie sau fluctuează tensiunea, mai ales seara.', cuvinte_cheie: ['lumina', 'palpaie', 'toata', 'casa', 'tensiune', 'fluctuatie', 'retea', 'branșament'], solutie_rezumat: 'Problemă la rețeaua electrică stradală sau la branșamentul blocului. Nu e remediu DIY.', dificultate: 'Avansat', timp_estimat: 'Depinde de furnizor', materiale: [], cand_specialist: 'Sună imediat distribuitorul local de energie electrică.' },

  { id: 'el_009', categorie: 'electric', titlu: 'LED-uri care se sting prematur', problema: 'Becurile LED se ard după câteva luni deși ar trebui să dureze ani.', cuvinte_cheie: ['led', 'sting', 'ard', 'prematur', 'driver', 'calitate', 'temperatura', 'supratensiune'], solutie_rezumat: 'Folosește LED-uri de calitate cu driver intern bun. Verifică dacă temperatura în doze e prea mare.', dificultate: 'Ușor', timp_estimat: '15 min', materiale: ['LED-uri calitate superioară (brand recunoscut)'], cand_specialist: 'Dacă se ard pe mai multe circuite simultan — problemă de tensiune.' },

  { id: 'el_010', categorie: 'electric', titlu: 'Priză de exterior defectă sau infiltrată de apă', problema: 'Priza din exterior nu funcționează sau prezintă urme de oxidare și umezeală.', cuvinte_cheie: ['priza', 'exterior', 'apa', 'umiditate', 'oxidare', 'ip44', 'etansa', 'umeda'], solutie_rezumat: 'Înlocuiește cu priză IP44 (etanșă la apă) specifică exterior. Verifică dozele pentru infiltrații.', dificultate: 'Mediu', timp_estimat: '30-60 min', materiale: ['Priză exterior IP44', 'Carcasă etanșă'], cand_specialist: 'Oprește curentul la tablou înainte de orice intervenție.' },

  { id: 'el_011', categorie: 'electric', titlu: 'Detector de fum care bip-uiește constant', problema: 'Detectorul de fum emite beep-uri intermitente fără motiv aparent.', cuvinte_cheie: ['detector', 'fum', 'alarma', 'bip', 'baterie', 'test', 'praf'], solutie_rezumat: 'De obicei bateria e descărcată. Înlocuiește bateria 9V. Curăță cu aer comprimat de praf.', dificultate: 'Foarte ușor', timp_estimat: '5 min', materiale: ['Baterie 9V'], cand_specialist: 'Niciodată — operațiune simplă.' },

  { id: 'el_012', categorie: 'electric', titlu: 'Termostat programabil nu funcționează', problema: 'Termostatul nu pornește/oprește centrala la temperaturile setate.', cuvinte_cheie: ['termostat', 'programabil', 'centrala', 'temperatura', 'setare', 'baterie', 'calibrare'], solutie_rezumat: 'Verifică bateriile termostatului. Resetează la setările din fabrică. Verifică cablajul de control.', dificultate: 'Ușor-Mediu', timp_estimat: '20-30 min', materiale: ['Baterii AA', 'Manual termostat'], cand_specialist: 'Dacă după resetare tot nu funcționează — posibil defect intern.' },

  { id: 'el_013', categorie: 'electric', titlu: 'Cablu prelungitor supraîncălzit', problema: 'Cablul prelungitor sau bara de prize devine fierbinte la atingere.', cuvinte_cheie: ['prelungitor', 'bara', 'prize', 'supraincalzit', 'fierbinte', 'suprasarcina', 'pericol'], solutie_rezumat: 'Reduce numărul de aparate conectate. Înlocuiește cu prelungitor cu secțiunea cablului mai mare.', dificultate: 'Ușor', timp_estimat: '5 min', materiale: ['Prelungitor cu secțiune 3x1.5mm² sau mai mare'], cand_specialist: 'Dacă prelungitorul miroase a ars — aruncă-l imediat.' },

  { id: 'el_014', categorie: 'electric', titlu: 'Centrală termică nu pornește', problema: 'Centrala de apartament nu pornește sau afișează cod de eroare.', cuvinte_cheie: ['centrala', 'termica', 'porneste', 'eroare', 'cod', 'presiune', 'gaz', 'resetare'], solutie_rezumat: 'Verifică presiunea apei în sistemul de încălzire (1.5-2 bar). Resetează cu butonul reset. Verifică gazul.', dificultate: 'Mediu', timp_estimat: '15-30 min', materiale: ['Manual centrală'], cand_specialist: 'Obligatoriu pentru intervenții la gaz sau interior centrală.' },

  { id: 'el_015', categorie: 'electric', titlu: 'Sonerie sau interfon defect', problema: 'Soneria de ușă sau interfonul nu mai funcționează, nu sună sau nu se aude.', cuvinte_cheie: ['sonerie', 'interfon', 'defect', 'suna', 'transformator', 'buton', 'cablu'], solutie_rezumat: 'Verifică transformatorul soneriei (8-12V). Înlocuiește butonul de sonerie dacă are contact oxidat.', dificultate: 'Ușor', timp_estimat: '20-40 min', materiale: ['Buton sonerie', 'Transformator 8V', 'Cablu bifilat'], cand_specialist: 'Nu e necesar pentru sonerie simplă.' },

  // ── CONSTRUCȚII (con_001 – con_015) ────────────────────────────────────────

  { id: 'con_001', categorie: 'constructii', titlu: 'Fisuri în perete de apartament', problema: 'Au apărut fisuri pe peretele interior, fie orizontale, fie verticale sau diagonale.', cuvinte_cheie: ['fisuri', 'perete', 'crapaturi', 'tencuiala', 'structural', 'umiditate', 'tasare'], solutie_rezumat: 'Fisuri fine superficiale: chituiește și revopsește. Fisuri largi sau active: verificare structurală obligatorie.', dificultate: 'Ușor-Avansat', timp_estimat: '1-8 ore', materiale: ['Chit fisuri', 'Bandă armătură', 'Vopsea lavabilă'], cand_specialist: 'Dacă fisura e mai lată de 5mm sau apare rapid — inginer structurist.' },

  { id: 'con_002', categorie: 'constructii', titlu: 'Igrasie și umezeală pe pereți', problema: 'Pete de umezeală sau mucegai pe pereți, mai ales în colțuri și la baza pereților.', cuvinte_cheie: ['igrasie', 'umiditate', 'mucegai', 'pete', 'perete', 'condensare', 'izolatie', 'infiltratie'], solutie_rezumat: 'Tratează cu soluție antimucegai. Îmbunătățește ventilația. Verifică termoizolația pereților exteriori.', dificultate: 'Mediu', timp_estimat: '2-8 ore', materiale: ['Soluție antimucegai', 'Vopsea hidrofugă', 'Grund izolant'], cand_specialist: 'Dacă vine din exteriorul clădirii sau din terenul de fundație.' },

  { id: 'con_003', categorie: 'constructii', titlu: 'Tencuială care se desface de pe perete', problema: 'Tencuiala se umflă, crapă și cade în bucăți de pe perete sau tavan.', cuvinte_cheie: ['tencuiala', 'cade', 'desface', 'perete', 'tavan', 'reparatie', 'amorsa', 'grund'], solutie_rezumat: 'Îndepărtează porțiunile slabe, curăță, grunduiește și retencuiește cu mortar de reparații.', dificultate: 'Mediu', timp_estimat: '4-8 ore + uscare', materiale: ['Mortar reparații', 'Grund contact', 'Gletuit finisaj'], cand_specialist: 'Dacă tencuiala cade pe suprafețe mari sau tavan — risc de accidentare.' },

  { id: 'con_004', categorie: 'constructii', titlu: 'Gresie sau faianță care se desprinde', problema: 'Plăci de gresie sau faianță s-au desprins de pe podea sau perete.', cuvinte_cheie: ['gresie', 'faianta', 'desprins', 'lipire', 'adeziv', 'rost', 'inlocuire', 'placi'], solutie_rezumat: 'Curăță bine suprafața, aplică adeziv flex și prinde din nou placa. Refă rosturile cu chit de rost.', dificultate: 'Mediu', timp_estimat: '2-4 ore + 24h uscare', materiale: ['Adeziv flex gresie', 'Chit rost', 'Spaclu dințat'], cand_specialist: 'Dacă se desprind în masă — posibil substrat umed sau insuficient pregătit.' },

  { id: 'con_005', categorie: 'constructii', titlu: 'Parchet care scârțâie la mers', problema: 'Parchetul scoate zgomote de scârțâit când mergi pe el, mai ales în anumite zone.', cuvinte_cheie: ['parchet', 'scartiie', 'scartait', 'podea', 'lemn', 'sapa', 'lipire', 'dilatare'], solutie_rezumat: 'Injectează adeziv PVA diluat în crăpăturile dintre lamele. Fixează cu șuruburi invizibile.', dificultate: 'Mediu', timp_estimat: '2-4 ore', materiale: ['Adeziv parchet', 'Șuruburi speciale parchet', 'Putty lemn'], cand_specialist: 'Dacă întreaga suprafață scârțâie — posibil substrat compromis.' },

  { id: 'con_006', categorie: 'constructii', titlu: 'Fereastră care nu se închide etanș', problema: 'Fereastra lasă aer rece să intre, se simte curent sau condensul apare pe rama interioară.', cuvinte_cheie: ['fereastra', 'garnitura', 'etansare', 'curent', 'aer', 'reglare', 'balamale', 'pvc'], solutie_rezumat: 'Înlocuiește garnitura perimetrală. Reglează balamalele și calacanele pentru presiune uniformă.', dificultate: 'Ușor', timp_estimat: '30-60 min', materiale: ['Garnitură fereastră PVC', 'Spray lubrifiant balamale'], cand_specialist: 'Dacă rama e deformată sau geamul e fisurat.' },

  { id: 'con_007', categorie: 'constructii', titlu: 'Ușă de interior care atârnă sau nu se închide', problema: 'Ușa se lovește de tocul ușii, nu se închide complet sau se deschide singură.', cuvinte_cheie: ['usa', 'atarna', 'inchide', 'balamale', 'reglare', 'toc', 'balanta', 'frecare'], solutie_rezumat: 'Reglează balamalele (cele moderne au reglaj 3D). Strânge șuruburile slăbite.', dificultate: 'Ușor', timp_estimat: '15-30 min', materiale: ['Cheie hex', 'Șuruburi inox', 'Spray lubrifiant'], cand_specialist: 'Dacă tocul ușii e deformat sau pereții s-au mișcat.' },

  { id: 'con_008', categorie: 'constructii', titlu: 'Tavan cu pete de umezeală de la vecin', problema: 'Pete maronii sau galbene au apărut pe tavan, posibil infiltrație de la etajul superior.', cuvinte_cheie: ['tavan', 'pete', 'umezeala', 'infiltratie', 'vecin', 'scurgere', 'reparatie'], solutie_rezumat: 'Identifică și oprește sursa (vecin de deasupra). Tratează cu grundant hidrofug și repictează.', dificultate: 'Mediu', timp_estimat: '4-8 ore + 48h uscare', materiale: ['Grund hidrofug', 'Vopsea plafon', 'Chit reparații'], cand_specialist: 'Dacă structura tavanului e afectată sau picură activ.' },

  { id: 'con_009', categorie: 'constructii', titlu: 'Podea de beton crăpată în garaj sau subsol', problema: 'Betonul de pe podea are fisuri, se fărâmițează sau are porțiuni denivelate.', cuvinte_cheie: ['beton', 'podea', 'fisura', 'crapata', 'garaj', 'subsol', 'mortar', 'epoxidic'], solutie_rezumat: 'Fisuri mici: umple cu mortar epoxidic fluid. Zone mari deteriorate: demolare și turnare nouă.', dificultate: 'Mediu-Avansat', timp_estimat: '4-16 ore', materiale: ['Mortar epoxidic', 'Grund penetrant', 'Amorsa beton'], cand_specialist: 'Dacă fisurile sunt structurale (fundație) — inginer de structuri.' },

  { id: 'con_010', categorie: 'constructii', titlu: 'Izolație termică insuficientă — perete rece', problema: 'Peretele exterior e rece iarna, condensul apare pe interior, facturile la energie sunt mari.', cuvinte_cheie: ['izolatie', 'termica', 'perete', 'rece', 'condensat', 'polistiren', 'vata', 'termoizolatie'], solutie_rezumat: 'Adaugă izolație termică la exterior (polistiren + tencuială) sau interior (gips-carton cu vatămineral).', dificultate: 'Avansat', timp_estimat: 'Câteva zile', materiale: ['Polistiren EPS 10cm', 'Adeziv termoizolant', 'Tencuială armată'], cand_specialist: 'Recomandabil pentru lucrări de amploare.' },

  { id: 'con_011', categorie: 'constructii', titlu: 'Scări interioare care scârțâie', problema: 'Treptele de lemn ale scărilor interioare fac zgomot la urcat sau coborât.', cuvinte_cheie: ['scari', 'trepte', 'scartiie', 'lemn', 'fixare', 'suruburi', 'adeziv', 'podea'], solutie_rezumat: 'Fixează treptele cu șuruburi din interior. Injectează adeziv în crăpături. Umple golurile cu chit lemn.', dificultate: 'Mediu', timp_estimat: '2-4 ore', materiale: ['Șuruburi inox', 'Adeziv lemn PVA', 'Putty lemn'], cand_specialist: 'Dacă structura scărilor (grinda centrală) e afectată.' },

  { id: 'con_012', categorie: 'constructii', titlu: 'Perete de gips-carton cu găuri sau deteriorat', problema: 'Peretele fals din gips-carton are găuri, lovituri sau porțiuni umede.', cuvinte_cheie: ['gips', 'carton', 'gaura', 'deteriorat', 'placa', 'inlocuire', 'chit', 'spaclu'], solutie_rezumat: 'Găuri mici: chit gips + armare cu bandă. Găuri mari: decupează și înlocuiește patch-ul cu placă nouă.', dificultate: 'Ușor-Mediu', timp_estimat: '1-4 ore', materiale: ['Chit gips', 'Bandă armatură', 'Patch gips-carton'], cand_specialist: 'Nu e necesar pentru reparații mici.' },

  { id: 'con_013', categorie: 'constructii', titlu: 'Balcon cu infiltrații de apă', problema: 'Apa de ploaie intră pe balcon sau terasa și ajunge pe podea sau perete interior.', cuvinte_cheie: ['balcon', 'terasa', 'infiltratie', 'apa', 'ploaie', 'hidroizolatie', 'panta', 'scurgere'], solutie_rezumat: 'Aplică hidroizolație elastică (membrană sau mortar hidrofug). Verifică și curăță scurgerile de pe balcon.', dificultate: 'Mediu', timp_estimat: '4-8 ore + 48h uscare', materiale: ['Membrană hidroizolantă', 'Mortar hidroizolant', 'Grund'], cand_specialist: 'Dacă structura balconului e afectată — fisuri în beton armat.' },

  { id: 'con_014', categorie: 'constructii', titlu: 'Vopsea care se coajă de pe pereți', problema: 'Vopseaua de pe pereți sau tavan se coajă, bășicuiește sau cade în fâșii.', cuvinte_cheie: ['vopsea', 'coaja', 'basicuieste', 'cade', 'perete', 'tavan', 'umiditate', 'grund'], solutie_rezumat: 'Îndepărtează tot, curăță, grunduiește și revopsește. Verifică umiditatea peretelui înainte.', dificultate: 'Ușor', timp_estimat: '4-8 ore', materiale: ['Grund izolant', 'Vopsea lavabilă de calitate', 'Glet finisaj'], cand_specialist: 'Dacă vine din probleme de umiditate — rezolvă mai întâi cauza.' },

  { id: 'con_015', categorie: 'constructii', titlu: 'Ușă exterior care lasă curenți de aer', problema: 'Ușa de intrare în apartament sau casă are spații pe lângă toc prin care intră aer rece.', cuvinte_cheie: ['usa', 'exterior', 'curent', 'aer', 'garnitura', 'prag', 'etansare', 'baie'], solutie_rezumat: 'Montează garnitură perimetrală autoadezivă și prag cu burete sau periuță de etanșare.', dificultate: 'Foarte ușor', timp_estimat: '30-60 min', materiale: ['Garnitură autoadezivă', 'Prag etanșare', 'Silicon transparent'], cand_specialist: 'Nu e necesar.' },

  // ── MOBILĂ (mob_001 – mob_015) ─────────────────────────────────────────────

  { id: 'mob_001', categorie: 'mobila', titlu: 'Ușă de dulap care nu se închide aliniat', problema: 'Ușa dulapului nu se aliniază cu cealaltă ușă, lasă spațiu inegal sau se deschide singură.', cuvinte_cheie: ['usa', 'dulap', 'balamale', 'reglare', 'inchide', 'aliniere', 'hex', 'ajustare'], solutie_rezumat: 'Reglează balamalele cu cheia hex: șurubul lateral pentru aliniere stânga-dreapta, cel central pentru adâncime.', dificultate: 'Foarte ușor', timp_estimat: '10-15 min', materiale: ['Cheie hex 2-4mm'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_002', categorie: 'mobila', titlu: 'Sertar blocat sau care iese din șine', problema: 'Sertarul nu se mai trage ușor, e blocat sau iese complet din glisierele lui.', cuvinte_cheie: ['sertar', 'blocat', 'sina', 'glisiera', 'iese', 'lubrifiere', 'reglare', 'montaj'], solutie_rezumat: 'Verifică și curăță glisierele. Lubrifie cu ceară de lumânare sau spray silicon. Repoziționează șinele.', dificultate: 'Ușor', timp_estimat: '15-30 min', materiale: ['Spray silicon', 'Ceară lumânare', 'Șurubelnița'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_003', categorie: 'mobila', titlu: 'Scaun cu picioare slabe sau care se clatină', problema: 'Scaunul se clatină, picioarele s-au slăbit din îmbinări sau unul e mai scurt.', cuvinte_cheie: ['scaun', 'clatina', 'picior', 'imbinare', 'adeziv', 'surub', 'ranfort', 'consolidare'], solutie_rezumat: 'Demontează, curăță, aplică adeziv PVA la îmbinări și reasamblează cu colier de strângere.', dificultate: 'Ușor', timp_estimat: '1 oră + 4h uscare', materiale: ['Adeziv PVA', 'Colier strângere mobilă', 'Pene lemn'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_004', categorie: 'mobila', titlu: 'Suprafață masă sau birou zgâriată sau deteriorată', problema: 'Blatul mesei are zgârieturi adânci, pete sau finisajul s-a deteriorat.', cuvinte_cheie: ['masa', 'birou', 'balt', 'zgarietura', 'deteriorat', 'finisaj', 'reparatie', 'ulei', 'lac'], solutie_rezumat: 'Zgârieturi mici: ceară de mobilă sau marker pentru lemn. Zgârieturi adânci: șlefuire și relacuire.', dificultate: 'Ușor-Mediu', timp_estimat: '30 min - 4 ore', materiale: ['Ceară mobilă', 'Marker lemn', 'Lac mobilă', 'Hârtie șmirghel'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_005', categorie: 'mobila', titlu: 'Pat cu șine de susținere rupte', problema: 'Șinele de lemn sau metal care susțin salteaua s-au rupt sau au ieșit din locaș.', cuvinte_cheie: ['pat', 'sina', 'lamela', 'rupe', 'sparge', 'saltea', 'inlocuire', 'sustinere'], solutie_rezumat: 'Înlocuiește lamelele rupte cu unele noi (dimensiune standard 63cm lățime). Disponibile la orice magazin de mobilă.', dificultate: 'Foarte ușor', timp_estimat: '10-20 min', materiale: ['Lamele pat înlocuitor'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_006', categorie: 'mobila', titlu: 'Bibliotecă sau raft care se încovoaie', problema: 'Polița bibliotecii sau raftul s-a încovoiat sub greutatea cărților.', cuvinte_cheie: ['raft', 'biblioteca', 'incovoia', 'sageat', 'greutate', 'suport', 'consolidare', 'lemn'], solutie_rezumat: 'Adaugă suport metalic intermediar sub poliță. Sau înlocuiește cu placă mai groasă (PAL 25mm sau lemn masiv).', dificultate: 'Ușor', timp_estimat: '30-60 min', materiale: ['Consolă metalică intermediară', 'Șuruburi', 'Placă PAL 25mm'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_007', categorie: 'mobila', titlu: 'Mâner de ușă sau sertar care s-a desprins', problema: 'Mânerul s-a rupt, șurubul s-a deșurupat sau mânerul e deteriorat.', cuvinte_cheie: ['maner', 'rupe', 'desprins', 'surub', 'inlocuire', 'usa', 'sertar', 'prindere'], solutie_rezumat: 'Strânge șurubul din interior sau înlocuiește mânerul cu unul nou (verifică distanța dintre găuri).', dificultate: 'Foarte ușor', timp_estimat: '5-10 min', materiale: ['Mâner înlocuitor', 'Șuruburi M4'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_008', categorie: 'mobila', titlu: 'Balamale uzate la dulap sau ușă mobilă', problema: 'Balamalele scârțâie, au joc exagerat sau mecanismul de amortizare nu mai funcționează.', cuvinte_cheie: ['balamale', 'uzate', 'scartiie', 'amortizare', 'slow', 'close', 'inlocuire', 'fixare'], solutie_rezumat: 'Lubrifie balamalele cu spray WD-40 sau înlocuiește-le cu unele noi (verifică diametrul cupei: 26mm, 35mm).', dificultate: 'Ușor', timp_estimat: '10-20 min', materiale: ['Balamale înlocuitor', 'WD-40', 'Cheie hex'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_009', categorie: 'mobila', titlu: 'Canapea sau fotoliu cu resort rupt', problema: 'Canapeaua are o porțiune moale care cedează, resort rupt sau pernă tasată.', cuvinte_cheie: ['canapea', 'fotoliu', 'resort', 'rupt', 'cedeza', 'tasata', 'perna', 'spuma', 'tapiterie'], solutie_rezumat: 'Înlocuiește resortul rupt sau adaugă placă de placaj sub pernele de șezut pentru suport temporar.', dificultate: 'Mediu', timp_estimat: '1-3 ore', materiale: ['Resort tip S înlocuitor', 'Placă placaj 12mm', 'Spumă poliuretanică'], cand_specialist: 'Pentru retapițare completă — tapițer profesionist.' },

  { id: 'mob_010', categorie: 'mobila', titlu: 'Masă de sufragerie cu picioare inegale', problema: 'Masa se clatină pentru că un picior e mai scurt sau podeaua e inegală.', cuvinte_cheie: ['masa', 'clatina', 'picior', 'inegal', 'nivelat', 'pana', 'talpa', 'reglabil'], solutie_rezumat: 'Montează tălpi reglabile sub fiecare picior. Sau adaugă o pană de lemn sub piciorul mai scurt.', dificultate: 'Foarte ușor', timp_estimat: '10-15 min', materiale: ['Tălpi reglabile înfiletate', 'Pene autoadezive'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_011', categorie: 'mobila', titlu: 'Dulap care nu stă drept sau e instabil', problema: 'Dulapul mare e înclinat, se clatină sau amenință să cadă.', cuvinte_cheie: ['dulap', 'inclinat', 'instabil', 'clatina', 'ancorare', 'perete', 'siguranta', 'nivel'], solutie_rezumat: 'Ancorat OBLIGATORIU în perete cu colțare metalice. Reglează picioarele pentru nivelare.', dificultate: 'Mediu', timp_estimat: '30-60 min', materiale: ['Colțare ancorare', 'Dibluri perete', 'Boloboc'], cand_specialist: 'Nu e necesar — dar OBLIGATORIU ancorat în perete (siguranță copii).' },

  { id: 'mob_012', categorie: 'mobila', titlu: 'Tapițerie ruptă la scaun sau canapea', problema: 'Stofa sau pielea scaunului/canapelei s-a rupt, s-a decolorat sau se deteriorează.', cuvinte_cheie: ['tapiterie', 'rupe', 'stofa', 'piele', 'reparatie', 'acoperire', 'husa'], solutie_rezumat: 'Soluție rapidă: husă de scaun/canapea. Soluție durabilă: retapițare cu material nou.', dificultate: 'Ușor-Mediu', timp_estimat: '30 min - 2 ore', materiale: ['Husă universală', 'Adeziv tapițerie', 'Material tapițerie'], cand_specialist: 'Tapițer pentru lucrări de calitate.' },

  { id: 'mob_013', categorie: 'mobila', titlu: 'Comodă cu sertare care nu se trag ușor', problema: 'Sertarele comodei se trag greu, se blochează sau scârțâie puternic.', cuvinte_cheie: ['comoda', 'sertar', 'greu', 'blocheaza', 'scartiie', 'lubrifiere', 'sina', 'ghidaj'], solutie_rezumat: 'Curăță ghidajele de praf. Aplică lumânare de ceară pe șine sau spray silicon.', dificultate: 'Foarte ușor', timp_estimat: '15-20 min', materiale: ['Ceară lumânare', 'Spray silicon', 'Cârpă'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_014', categorie: 'mobila', titlu: 'Pat sau comodă cu suruburi slăbite', problema: 'Mobila s-a desfăcut parțial, îmbinările fac zgomot sau piesele se mișcă.', cuvinte_cheie: ['pat', 'comoda', 'suruburi', 'slabite', 'imbinare', 'strang', 'consolidare', 'confirmate'], solutie_rezumat: 'Strânge toate confirmații cu cheia hex. Dacă găurile sunt lărgite, folosește dopuri de lemn cu adeziv.', dificultate: 'Ușor', timp_estimat: '20-30 min', materiale: ['Cheie hex', 'Dopuri lemn', 'Adeziv PVA'], cand_specialist: 'Nu e necesar.' },

  { id: 'mob_015', categorie: 'mobila', titlu: 'Oglindă sau poliță de perete căzută', problema: 'Oglinda sau raftul de perete a căzut, dibluurile au ieșit din perete.', cuvinte_cheie: ['oglinda', 'raft', 'perete', 'dibluri', 'prindere', 'cazut', 'remontare', 'ancorare'], solutie_rezumat: 'Identifică tipul peretelui (BCA, cărămidă, gips-carton) și folosește diblu corespunzător.', dificultate: 'Ușor', timp_estimat: '20-30 min', materiale: ['Dibluri potrivite', 'Șuruburi inox', 'Bormașină'], cand_specialist: 'Nu e necesar, dar verifică greutatea obiectului față de tipul de dibluri.' },

  // ── GRĂDINĂ (gra_001 – gra_015) ────────────────────────────────────────────

  { id: 'gra_001', categorie: 'gradina', titlu: 'Gazon uscat și îngălbenit', problema: 'Iarba din grădină s-a uscat, a îngălbenit sau are pete maronii.', cuvinte_cheie: ['gazon', 'uscat', 'galben', 'iarba', 'udare', 'fertilizare', 'aerare', 'sol'], solutie_rezumat: 'Udă profund de 2-3 ori pe săptămână. Fertilizează cu azot primăvara. Aerează solul compactat.', dificultate: 'Ușor', timp_estimat: 'Câteva săptămâni tratament', materiale: ['Îngrășământ gazon cu azot', 'Aerator sol'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_002', categorie: 'gradina', titlu: 'Sistem de irigații înfundat sau cu presiune slabă', problema: 'Aspersoarele nu funcționează corect, unele zone nu se udă, presiunea e slabă.', cuvinte_cheie: ['irigatie', 'aspersor', 'infundat', 'presiune', 'furtun', 'filtru', 'picurare'], solutie_rezumat: 'Curăță filtrele sistemului. Verifică furtunurile pentru deformări. Curăță duzele aspersonarelor.', dificultate: 'Ușor-Mediu', timp_estimat: '1-2 ore', materiale: ['Filtru irigație', 'Duze aspersor', 'Bandă teflon'], cand_specialist: 'Nu e necesar pentru sisteme simple.' },

  { id: 'gra_003', categorie: 'gradina', titlu: 'Gard din lemn deteriorat sau putrezit', problema: 'Gardul din lemn are scânduri putrezite, crăpate sau vopseaua s-a cojit.', cuvinte_cheie: ['gard', 'lemn', 'putrezit', 'crapaturi', 'vopsea', 'tratament', 'inlocuire', 'impregnare'], solutie_rezumat: 'Tratează cu soluție impregnant și biocid. Înlocuiește scândurile putrezite. Revopsește cu lazură sau vopsea exterior.', dificultate: 'Mediu', timp_estimat: '4-8 ore', materiale: ['Impregnant lemn', 'Lazură exterior', 'Scânduri înlocuitor'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_004', categorie: 'gradina', titlu: 'Pompă de grădină nu pornește sau debit slab', problema: 'Pompa de grădină nu pornește, face zgomot dar nu pompează sau debitul e mic.', cuvinte_cheie: ['pompa', 'gradina', 'porneste', 'debit', 'slab', 'impeller', 'filtru', 'amorsare'], solutie_rezumat: 'Verifică dacă pompa e amorsată (umplută cu apă). Curăță filtrul de aspirație. Verifică condensatorul.', dificultate: 'Mediu', timp_estimat: '30-60 min', materiale: ['Condensator pompa', 'Garnituri', 'Filtru aspirație'], cand_specialist: 'Dacă motorul pompei e ars — service electrician.' },

  { id: 'gra_005', categorie: 'gradina', titlu: 'Roșii cu boli sau pete pe frunze', problema: 'Frunzele de roșii au pete galbene, maronii sau negre, plantele se ofilesc.', cuvinte_cheie: ['rosii', 'boli', 'pete', 'frunze', 'mana', 'alternaria', 'fungicid', 'tratament'], solutie_rezumat: 'Tratează cu fungicid pe bază de cupru (zeamă bordeleză). Îndepărtează frunzele afectate. Udă doar la bază.', dificultate: 'Ușor', timp_estimat: '1-2 ore', materiale: ['Zeamă bordeleză', 'Fungicid sistemic', 'Pulverizator'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_006', categorie: 'gradina', titlu: 'Copac sau arbust cu ramuri uscate', problema: 'Ramurile unui copac s-au uscat, au scoarță crăpată sau nu mai au frunze primăvara.', cuvinte_cheie: ['copac', 'arbust', 'ramuri', 'uscate', 'taiere', 'toaletare', 'boala', 'fungicid'], solutie_rezumat: 'Taie ramurile uscate până în lemn sănătos. Tratează tăieturile cu mastic de altoire sau fungicid.', dificultate: 'Ușor-Mediu', timp_estimat: '1-4 ore', materiale: ['Ferăstrău copaci', 'Mastic altoire', 'Dezinfectant tăieturi'], cand_specialist: 'Copaci mari lângă clădiri sau linii electrice — arborist certificat.' },

  { id: 'gra_007', categorie: 'gradina', titlu: 'Sol compactat — plantele cresc greu', problema: 'Solul e tare ca betonul, apa nu se absoarbe și plantele nu cresc bine.', cuvinte_cheie: ['sol', 'compactat', 'tare', 'aerare', 'afanare', 'compost', 'structura', 'nisip'], solutie_rezumat: 'Aerează cu forca sau aeratorul manual. Incorporează compost și nisip grosier pentru structură.', dificultate: 'Mediu', timp_estimat: '2-4 ore', materiale: ['Forcă', 'Compost', 'Nisip grosier', 'Îngrășământ humus'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_008', categorie: 'gradina', titlu: 'Dăunători pe plante — afide sau omizi', problema: 'Plantele au colonii de afide (păduchi de plante), omizi sau alte insecte dăunătoare.', cuvinte_cheie: ['afide', 'paduchi', 'omizi', 'daunatori', 'insecte', 'insecticid', 'tratament', 'bio'], solutie_rezumat: 'Tratament bio: soluție de apă cu săpun sau ulei de neem. Tratament chimic: insecticid sistemic.', dificultate: 'Ușor', timp_estimat: '30-60 min', materiale: ['Ulei neem', 'Săpun insecticid', 'Pulverizator'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_009', categorie: 'gradina', titlu: 'Gard viu sau tufe care se usucă parțial', problema: 'Tuia, leandrul sau gardul viu are zone brune, uscate sau frunzele cad anormal.', cuvinte_cheie: ['gard', 'viu', 'tuia', 'usuca', 'brun', 'ciuperci', 'fungicid', 'phaephospthora'], solutie_rezumat: 'Verifică drenajul (rădăcinile nu trebuie să stea în apă). Tratează cu fungicid sistemic. Taie porțiunile uscate.', dificultate: 'Ușor', timp_estimat: '1-2 ore', materiale: ['Fungicid sistemic', 'Îngrășământ special conifere'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_010', categorie: 'gradina', titlu: 'Furtun de grădină spart sau cu scurgeri', problema: 'Furtunul de grădină are fisuri, bășici sau se scurge la fitinguri.', cuvinte_cheie: ['furtun', 'gradina', 'spart', 'scurgere', 'reparatie', 'fiting', 'conector', 'cuplaj'], solutie_rezumat: 'Fisuri mici: bandă pentru reparații furtun. Fisuri mari: taie și reunește cu conector de reparații.', dificultate: 'Foarte ușor', timp_estimat: '10-15 min', materiale: ['Conector reparații furtun', 'Bandă reparații furtun'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_011', categorie: 'gradina', titlu: 'Compostare incorectă — miros urât', problema: 'Compostul miroase urât (ouă clocite), e prea umed sau nu se descompune corect.', cuvinte_cheie: ['compost', 'miros', 'urat', 'umed', 'descompunere', 'brun', 'verde', 'aerare'], solutie_rezumat: 'Alternează materiale verzi (umede) cu brune (uscate). Aerează săptămânal. Adaugă paie sau carton.', dificultate: 'Ușor', timp_estimat: '30 min', materiale: ['Paie', 'Carton', 'Furca compost'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_012', categorie: 'gradina', titlu: 'Flori de grădină care se ofilesc rapid', problema: 'Florile plantate în grădină sau ghivece se ofilesc rapid deși le uzi.', cuvinte_cheie: ['flori', 'ofilesc', 'ghiveci', 'udare', 'drenaj', 'radacini', 'sol', 'arsuri', 'soare'], solutie_rezumat: 'Verifică drenajul (excesul de apă dăunează la fel ca lipsa). Verifică expunerea la soare vs. nevoile plantei.', dificultate: 'Ușor', timp_estimat: '30 min', materiale: ['Sol cu drenaj bun', 'Îngrășământ lichid'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_013', categorie: 'gradina', titlu: 'Mici rozătoare în grădină — cârtițe sau șoareci', problema: 'Apar movile de pământ sau galerii sub gazon, plantele dispar din pământ.', cuvinte_cheie: ['cartita', 'soarece', 'rozatoare', 'galerie', 'movile', 'capcana', 'alungare'], solutie_rezumat: 'Capcane mecanice sau electronice. Vibrații în sol (țăruși cu morisca). Plante respingătoare (talpa-gâștei).', dificultate: 'Mediu', timp_estimat: 'Câteva zile tratament', materiale: ['Capcane cârtițe', 'Turbine sol', 'Plante respingătoare'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_014', categorie: 'gradina', titlu: 'Iarbă cu buruieni invazive', problema: 'Gazonul e invadat de buruieni, pir, susai sau mătăciune care se răspândesc rapid.', cuvinte_cheie: ['buruieni', 'gazon', 'pir', 'mataciuna', 'erbicid', 'plivire', 'invazie', 'control'], solutie_rezumat: 'Plivire manuală pentru suprafețe mici. Erbicid selectiv pentru gazon (nu dăunează ierbii) pentru suprafețe mari.', dificultate: 'Ușor-Mediu', timp_estimat: '1-4 ore', materiale: ['Erbicid selectiv gazon', 'Greblă rădăcini', 'Sapă'], cand_specialist: 'Nu e necesar.' },

  { id: 'gra_015', categorie: 'gradina', titlu: 'Plantație de legume atacată de boli fungice', problema: 'Mana sau alte boli fungice atacă castraveții, cartofii sau ardeii.', cuvinte_cheie: ['legume', 'mana', 'fungus', 'ciuperca', 'castraveti', 'cartofi', 'ardei', 'tratament', 'preventiv'], solutie_rezumat: 'Tratament preventiv cu zeamă bordeleză la 10-14 zile. Evită udarea pe frunze. Rotatie culturi anual.', dificultate: 'Ușor', timp_estimat: '30-60 min', materiale: ['Zeamă bordeleză', 'Fungicid Ridomil', 'Pulverizator'], cand_specialist: 'Nu e necesar.' },
];

// ─── Upload function ───────────────────────────────────────────────────────────

export async function uploadAllScenarii(): Promise<{ success: number; errors: number }> {
  let success = 0;
  let errors = 0;

  for (const scenariu of SCENARII) {
    try {
      const ref = doc(db, 'rag_knowledge', scenariu.categorie, 'scenarii', scenariu.id);
      await setDoc(ref, scenariu);
      console.log(`✓ ${scenariu.id}`);
      success++;
    } catch (error) {
      console.error(`✗ ${scenariu.id}:`, error);
      errors++;
    }
  }

  console.log(`\nUpload complet: ${success} succes, ${errors} erori`);
  return { success, errors };
}
