/**
 * RAG Upload — încarcă cele 75 scenarii în Firestore.
 *
 * Structura Firestore: /rag_knowledge/{categorie}/scenarii/{id}
 *
 * NOTĂ Security Rules: adaugă în Firebase Console → Firestore → Rules:
 *   match /rag_knowledge/{cat}/scenarii/{id} {
 *     allow write: if false; // scrie doar prin Admin SDK (scripts/uploadRAG.js)
 *     allow read:  if request.auth != null;
 *   }
 *
 * Pentru upload producție folosește: node scripts/uploadRAG.js
 */

import { collection, doc, setDoc, writeBatch } from 'firebase/firestore';
import { db } from './config';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SolutieRAG {
  dificultate: string;
  timp_estimat: string;
  pasi: string[];
  sfat_pro: string;
}

export interface ScenariuRAG {
  id: string;
  categorie: string;
  titlu: string;
  problema: string;
  cuvinte_cheie: string[];
  cauze_posibile: string[];
  solutie: SolutieRAG;
  materiale_necesare: string[];
  cand_chemi_specialistul: string;
  embedding: number[];
}

// ── Upload function ───────────────────────────────────────────────────────────

export async function uploadScenarii(
  scenarii: ScenariuRAG[],
  onProgress?: (done: number, total: number) => void
): Promise<{ success: number; errors: number }> {
  let success = 0;
  let errors = 0;
  const BATCH_SIZE = 20;

  for (let i = 0; i < scenarii.length; i += BATCH_SIZE) {
    const batch = writeBatch(db);
    const chunk = scenarii.slice(i, i + BATCH_SIZE);
    chunk.forEach(s => {
      const ref = doc(collection(db, 'rag_knowledge', s.categorie, 'scenarii'), s.id);
      batch.set(ref, s);
    });
    try {
      await batch.commit();
      success += chunk.length;
    } catch {
      errors += chunk.length;
    }
    onProgress?.(Math.min(i + BATCH_SIZE, scenarii.length), scenarii.length);
  }

  return { success, errors };
}

// ── Cele 75 scenarii ──────────────────────────────────────────────────────────

export const SCENARII_RAG: ScenariuRAG[] = [

  // ── SANITARE ────────────────────────────────────────────────────────────────

  {
    id: 'san_001', categorie: 'sanitare',
    titlu: 'Robinet bucătărie care picură',
    problema: 'Robinetul de la bucătărie picură continuu chiar și când este închis complet.',
    cuvinte_cheie: ['robinet', 'picura', 'bucatarie', 'garnitura', 'cartus', 'ceramic'],
    cauze_posibile: ['Garnitură de cauciuc uzată sau deformată', 'Cartuș ceramic deteriorat sau calcaros'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30-45 min',
      pasi: ['Închide robinetul de apă de sub chiuvetă', 'Demontează mânerul (șurub ascuns sub capac decorativ)', 'Scoate și înlocuiește garnitura sau cartușul ceramic', 'Reasamblează și testează'],
      sfat_pro: 'Unge ușor garnitura nouă cu silicon înainte de montaj pentru etanșare perfectă și durabilitate crescută.',
    },
    materiale_necesare: ['Garnitură robinet', 'Unsoare silicon', 'Cheie reglabilă'],
    cand_chemi_specialistul: 'Dacă după înlocuire tot picură sau dacă robinetul e vechi de peste 15 ani.',
    embedding: [],
  },
  {
    id: 'san_002', categorie: 'sanitare',
    titlu: 'WC care curge continuu în rezervor',
    problema: 'Se aude zgomot continuu de apă în vasul de toaletă, rezervorul nu se oprește.',
    cuvinte_cheie: ['wc', 'toaleta', 'rezervor', 'curge', 'zgomot', 'apa', 'plutitor', 'supapa'],
    cauze_posibile: ['Supapă de umplere defectă sau uzată', 'Plutitor reglat incorect sau perforat'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-30 min',
      pasi: ['Ridică capacul rezervorului și observă nivelul apei', 'Reglează înălțimea plutitorului (înșurubează sau îndoaie brațul)', 'Dacă nu ajunge: înlocuiește supapa de umplere universală', 'Testează prin tragerea apei de 2-3 ori'],
      sfat_pro: 'Supapele universale costă sub 15 RON și se montează în 20 de minute — nu merită reparată una veche.',
    },
    materiale_necesare: ['Supapă plutitor universală', 'Garnitură cauciuc'],
    cand_chemi_specialistul: 'Dacă rezervorul are fisuri sau supapa nouă tot nu etanșează.',
    embedding: [],
  },
  {
    id: 'san_003', categorie: 'sanitare',
    titlu: 'Țeavă care curge sub chiuvetă',
    problema: 'Se observă picături sau baltă de apă sub chiuvetă, venind de la îmbinările țevilor.',
    cuvinte_cheie: ['teava', 'chiuveta', 'curge', 'scurgere', 'sifon', 'imbinare', 'etansare'],
    cauze_posibile: ['Garnituri de la sifon uzate sau strânse insuficient', 'Teflon lipsă sau deteriorat la filet'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '15-30 min',
      pasi: ['Pune un lighean sub chiuvetă', 'Identifică exact îmbinarea care curge', 'Strânge piulițele sifonului sau înlocuiește garniturile', 'Testează cu apa deschisă 2 minute'],
      sfat_pro: 'La îmbinările cu filet aplicată 3-4 straturi de teflon — nu te zgârcii, e piesa cheie a etanșării.',
    },
    materiale_necesare: ['Garnituri sifon', 'Teflon', 'Cheie pentru țevi'],
    cand_chemi_specialistul: 'Dacă țeava e crăpată sau corodată — necesită înlocuire.',
    embedding: [],
  },
  {
    id: 'san_004', categorie: 'sanitare',
    titlu: 'Presiune slabă la apă',
    problema: 'Apa curge slab la robinete, presiunea este mult mai mică decât normal.',
    cuvinte_cheie: ['presiune', 'apa', 'slab', 'robinet', 'filtru', 'calcar', 'aerator'],
    cauze_posibile: ['Aerator înfundat cu calcar', 'Filtru de sedimente colmatat', 'Problemă la rețeaua blocului'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-40 min',
      pasi: ['Deșurubează aeratorul de la robinet (capătul cu găurele)', 'Curăță cu soluție detartrant sau oțet 30 min', 'Montează la loc și testează presiunea', 'Dacă tot slab: verifică filtrul de sedimente de la intrarea apei'],
      sfat_pro: 'Aeratoarele se înfundă în 1-2 ani în zone cu apă calcaroasă. Curăță-le preventiv.',
    },
    materiale_necesare: ['Aerator de robinet', 'Soluție detartrant', 'Cheie reglabilă'],
    cand_chemi_specialistul: 'Dacă presiunea e slabă în toată casa — problemă la contorul de apă sau rețea.',
    embedding: [],
  },
  {
    id: 'san_005', categorie: 'sanitare',
    titlu: 'Apă caldă nu vine sau vine rece',
    problema: 'Nu există apă caldă sau vine apă caldă după mult timp de așteptare.',
    cuvinte_cheie: ['apa', 'calda', 'boiler', 'termostat', 'rezistenta', 'incalzire', 'electric'],
    cauze_posibile: ['Rezistență electrică arsă', 'Termostat defect sau setat greșit', 'Calcar excesiv pe rezistență'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '1-2 ore',
      pasi: ['Verifică dacă boilerul e pornit și LED-ul de funcționare e activ', 'Setează termostatul la 60°C dacă e mai jos', 'Testează rezistența cu multimetru (trebuie să indice ~20-30Ω)', 'Dacă e arsă: golește boilerul și înlocuiește rezistența'],
      sfat_pro: 'Detartrează boilerul o dată pe an — calcarul e principala cauză de ardere a rezistențelor.',
    },
    materiale_necesare: ['Rezistență boiler', 'Termostat boiler', 'Garnitură'],
    cand_chemi_specialistul: 'Dacă boilerul are peste 10 ani sau dacă e problemă de instalație electrică.',
    embedding: [],
  },
  {
    id: 'san_006', categorie: 'sanitare',
    titlu: 'Sifon chiuvetă înfundat',
    problema: 'Apa se scurge foarte lent sau deloc din chiuvetă sau cadă de baie.',
    cuvinte_cheie: ['sifon', 'infundat', 'scurgere', 'lent', 'chiuveta', 'cada', 'par', 'grasime'],
    cauze_posibile: ['Acumulare de păr și săpun în sifon', 'Grăsimi solidificate în conducte', 'Corp străin căzut în sifon'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-30 min',
      pasi: ['Încearcă mai întâi cu desfundatorul cu ventuzătare (10-15 pompe viguroase)', 'Toarnă soluție chimică desfundare și lasă 15-30 min', 'Dacă tot nu merge: demontează sifonul și curăță manual', 'Remontează cu garnituri noi și testează'],
      sfat_pro: 'Montează o sită de retenție a părului în fiecare lună — previne 90% din înfundări.',
    },
    materiale_necesare: ['Desfundator ventuza', 'Soluție desfundat', 'Mănuși'],
    cand_chemi_specialistul: 'Dacă înfundarea e mai adâncă în coloana de scurgere.',
    embedding: [],
  },
  {
    id: 'san_007', categorie: 'sanitare',
    titlu: 'Cabina de duș curge la baza',
    problema: 'Apa iese pe sub cabina de duș sau pe lângă ușă pe parchetul din baie.',
    cuvinte_cheie: ['dus', 'cabina', 'curge', 'scurgere', 'silicon', 'etansare', 'garnitura'],
    cauze_posibile: ['Silicon vechi fisurat sau dezlipit', 'Garnitură de jos a ușii uzată', 'Platou de duș nesigilat complet'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '1-2 ore + uscare 24h',
      pasi: ['Îndepărtează tot silicone-ul vechi cu bisturiul', 'Degresează cu alcool izopropilic 10 minute', 'Aplică un cordon continuu de silicon sanitar pe toată baza', 'Nu folosi dușul 24h — lasă să se vulcanizeze complet'],
      sfat_pro: 'Folosește silicon sanitar antifungic (cu biocid) — durează de 3× mai mult în mediul umed.',
    },
    materiale_necesare: ['Silicon sanitar antifungic', 'Pistol silicon', 'Alcool izopropilic'],
    cand_chemi_specialistul: 'Dacă placa de duș are fisuri sau dacă gresia e afectată de umezeală.',
    embedding: [],
  },
  {
    id: 'san_008', categorie: 'sanitare',
    titlu: 'Baterie monocomandă defectă',
    problema: 'Bateria cu mâner unic nu oprește complet apa sau curge pe lângă mâner.',
    cuvinte_cheie: ['baterie', 'monocomanda', 'maneta', 'cartus', 'ceramic', 'picura', 'scurgere'],
    cauze_posibile: ['Cartuș ceramic uzat sau calcaros', 'O-ring deteriorat pe axul cartuşului'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '45-60 min',
      pasi: ['Închide apa de sub chiuvetă', 'Scoate clapeta decorativă și deșurubează mânerul', 'Extrage cartușul cu cheia hex (notează diametrul: 35mm sau 40mm)', 'Montează cartuș ceramic nou identic'],
      sfat_pro: 'Fotografiază cartușul vechi înainte de a pleca la magazin — diametrul și marca contează.',
    },
    materiale_necesare: ['Cartuș ceramic 35/40mm', 'Unsoare silicon', 'Cheie hex'],
    cand_chemi_specialistul: 'Dacă bateria e veche și piesele nu mai sunt disponibile.',
    embedding: [],
  },
  {
    id: 'san_009', categorie: 'sanitare',
    titlu: 'Rezervor WC nu se umple sau se umple lent',
    problema: 'După tragere, rezervorul toaletei se umple foarte lent sau nu se umple deloc.',
    cuvinte_cheie: ['rezervor', 'wc', 'toaleta', 'umplere', 'lent', 'supapa', 'filtru', 'calcar'],
    cauze_posibile: ['Filtru de sedimente înfundat la intrarea în rezervor', 'Supapă de umplere parțial blocată de calcar'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-30 min',
      pasi: ['Închide robinetul de pe țeava rezervorului', 'Deșurubează conducta de alimentare și găsește filtrul mic de plasă', 'Curăță filtrul cu periuță sub jet de apă', 'Dacă nu ajută: înlocuiește supapa de umplere'],
      sfat_pro: 'Filtrul rezervorului se curăță o dată pe an — 5 minute care salvează supapa.',
    },
    materiale_necesare: ['Supapă umplere universală', 'Garnituri', 'Soluție detartrant'],
    cand_chemi_specialistul: 'Dacă presiunea în apartament e în general slabă — problemă la rețea.',
    embedding: [],
  },
  {
    id: 'san_010', categorie: 'sanitare',
    titlu: 'Miros neplăcut din canalizare',
    problema: 'Se simte miros de canalizare în baie sau bucătărie, mai ales dimineața.',
    cuvinte_cheie: ['miros', 'canalizare', 'sifon', 'uscat', 'gaz', 'baie', 'bucatarie'],
    cauze_posibile: ['Sifon uscat la aparatele rar folosite', 'Garnitură de bază WC deteriorată', 'Coloană de ventilație blocată'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '15-30 min',
      pasi: ['Toarnă 2L de apă în toate sifonele rar folosite (baie oaspeți, mașina de spălat)', 'Verifică garnitura de bază a vasului WC cu lumina telefonului', 'Înlocuiește garnitura dacă e crăpată', 'Aerisește 30 min — dacă persistă: coloană de ventilație'],
      sfat_pro: 'Adaugă o linguriță de ulei mineral în sifonele rar folosite — împiedică evaporarea apei.',
    },
    materiale_necesare: ['Soluție curățare canalizare', 'Silicon sanitar', 'Garnitură bază WC'],
    cand_chemi_specialistul: 'Dacă mirosul persistă după curățare — posibil problemă la coloana de ventilație.',
    embedding: [],
  },
  {
    id: 'san_011', categorie: 'sanitare',
    titlu: 'Robinet termostatat nu reglează temperatura',
    problema: 'Robinetul cu termostat nu menține temperatura setată sau apa iese mereu rece sau fierbinte.',
    cuvinte_cheie: ['termostat', 'robinet', 'temperatura', 'reglare', 'cartus', 'termostatat'],
    cauze_posibile: ['Cartuș termostatic uzat sau calcaros', 'Limitator de temperatură blocat'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '45-90 min',
      pasi: ['Extrage mânerul de temperatură', 'Verifică limitatorul de temperatură (buton de siguranță)', 'Calibrează limitatorul sau extrage cartușul termostatic', 'Înlocuiește cartușul cu model identic'],
      sfat_pro: 'Cartușele termostatice sunt sensibile la calcar — detartrează cu oțet înainte de înlocuire.',
    },
    materiale_necesare: ['Cartuș termostatic', 'Unsoare silicon'],
    cand_chemi_specialistul: 'Dacă marca nu mai are piese de schimb disponibile.',
    embedding: [],
  },
  {
    id: 'san_012', categorie: 'sanitare',
    titlu: 'Boiler electric face zgomot',
    problema: 'Boilerul face zgomote puternice de clocotit sau pocnit în timpul încălzirii.',
    cuvinte_cheie: ['boiler', 'zgomot', 'calcar', 'rezistenta', 'clocotit', 'pocnit', 'detartrat'],
    cauze_posibile: ['Depuneri groase de calcar pe rezistență', 'Reacție termică la stratul de calcar în contact cu apa'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '2-3 ore',
      pasi: ['Oprește boilerul și golește-l complet', 'Demontează rezistența (flanșă cu 6-8 șuruburi)', 'Scufundă rezistența în soluție detartrant 1-2 ore', 'Montează rezistența curată (sau nouă dacă e prea degradată)'],
      sfat_pro: 'Setează boilerul la 55-60°C în loc de 75°C — calcarul se depune mult mai lent.',
    },
    materiale_necesare: ['Soluție detartrant', 'Rezistență boiler', 'Garnitură flanșă'],
    cand_chemi_specialistul: 'Dacă boilerul are peste 8 ani și rezistența e puternic corodată.',
    embedding: [],
  },
  {
    id: 'san_013', categorie: 'sanitare',
    titlu: 'Calcar pe capul de duș — jet slab',
    problema: 'Jetul de la dușul de mână e slab sau iese în direcții greșite din cauza calcarului.',
    cuvinte_cheie: ['dus', 'cap', 'calcar', 'jet', 'slab', 'detartrant', 'orificit'],
    cauze_posibile: ['Orificii înfundate cu depuneri de calcar', 'Filtru intern colmatat'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '5 min + 3 ore înmuiat',
      pasi: ['Pune capul de duș într-o pungă cu oțet alb și fixează cu elastic', 'Lasă la înmuiat 2-3 ore (sau peste noapte pentru calcar dens)', 'Curăță orificiile blocate cu o scobitoare sau ac', 'Clătește cu apă caldă și testează jetul'],
      sfat_pro: 'Repetă lunar dacă apa e calcaroasă. Costă 0 lei și durează 5 minute.',
    },
    materiale_necesare: ['Oțet alb', 'Pungă plastic', 'Elastic'],
    cand_chemi_specialistul: 'Nu este necesar.',
    embedding: [],
  },
  {
    id: 'san_014', categorie: 'sanitare',
    titlu: 'Țeavă înghețată iarna',
    problema: 'Apa nu mai curge iarna la robinet, posibil țeavă înghețată.',
    cuvinte_cheie: ['teava', 'inghetata', 'iarna', 'frig', 'dezghetat', 'apa', 'inghet'],
    cauze_posibile: ['Temperaturi sub 0°C în spații neîncălzite (beci, balcon)', 'Izolație termică insuficientă a țevilor'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '30-120 min',
      pasi: ['NU deschide robinetul cu forță', 'Dezgheață lent cu foenul pe setarea medie (nu fierbinte)', 'Alternativ: prosoape calde cu apă caldă în jurul țevii', 'Izolează țeava cu spumă tubulară după dezghețare'],
      sfat_pro: 'NU folosi niciodată flacără (risc de incendiu și spargere). Foenul e singura soluție sigură.',
    },
    materiale_necesare: ['Foen', 'Prosoape calde', 'Spumă izolație țevi'],
    cand_chemi_specialistul: 'Dacă țeava s-a spart din cauza înghețului — intervenție urgentă.',
    embedding: [],
  },
  {
    id: 'san_015', categorie: 'sanitare',
    titlu: 'Robinetul de închidere principal nu funcționează',
    problema: 'Robinetul general de apă al apartamentului este blocat sau nu închide complet.',
    cuvinte_cheie: ['robinet', 'inchidere', 'principal', 'general', 'blocat', 'vana', 'apart'],
    cauze_posibile: ['Vana nefolosită ani de zile s-a blocat cu oxid', 'Garnitură interioară uzată care nu mai etanșează'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '1-2 ore',
      pasi: ['Pulverizează WD-40 pe axul vanei și lasă 15-30 min', 'Încearcă să miști treptat fără forță excesivă', 'Dacă e blocat total: înlocuiește cu vană sferică nouă (necesită închiderea coloanei)', 'Testează etanșarea după operațiune'],
      sfat_pro: 'Deschide și închide vana principală o dată la 6 luni — 30 secunde care previn blocarea.',
    },
    materiale_necesare: ['WD-40', 'Vană sferică 1/2"', 'Teflon', 'Cheie reglabilă'],
    cand_chemi_specialistul: 'Necesită închiderea apei pe coloana blocului — implică administratorul.',
    embedding: [],
  },

  // ── ELECTRIC ────────────────────────────────────────────────────────────────

  {
    id: 'el_001', categorie: 'electric',
    titlu: 'Siguranțe automate care sar frecvent',
    problema: 'Siguranța automată dintr-un circuit sare frecvent, mai ales când pornești aparate.',
    cuvinte_cheie: ['siguranta', 'automata', 'sare', 'circuit', 'suprasarcina', 'tablou', 'disjunctor'],
    cauze_posibile: ['Supraîncărcare circuit (prea multe aparate pe același circuit)', 'Siguranță cu amperaj prea mic față de consum', 'Scurtcircuit la un aparat conectat'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '30-60 min',
      pasi: ['Deconectează toate aparatele de pe circuitul respectiv', 'Pornește siguranța și conectează aparatele unul câte unul', 'Identifică aparatul sau combinația care face să sară', 'Redistribuie consumatorii mari pe circuite diferite'],
      sfat_pro: 'Suma ampilor aparatelor nu trebuie să depășească 80% din amperajul siguranței.',
    },
    materiale_necesare: ['Siguranță automată calibrată corect'],
    cand_chemi_specialistul: 'OBLIGATORIU pentru înlocuirea siguranței — risc de electrocutare.',
    embedding: [],
  },
  {
    id: 'el_002', categorie: 'electric',
    titlu: 'Priză care nu funcționează',
    problema: 'O priză din casă nu alimentează aparatele conectate la ea.',
    cuvinte_cheie: ['priza', 'functioneaza', 'curent', 'contact', 'faze', 'multimetru', 'nul'],
    cauze_posibile: ['Siguranța circuitului a căzut', 'Contact oxidat sau slăbit în doză', 'Priza deteriorată mecanic'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '15-45 min',
      pasi: ['Verifică tabloul electric — dacă o siguranță e josă, ridic-o', 'Testează priza cu un tester sau alt aparat', 'Oprește curentul la tablou înainte de orice intervenție în doză', 'Verifică conexiunile și strânge-le sau înlocuiește priza'],
      sfat_pro: 'Niciodată nu lucra la prize cu curentul pornit — oprește siguranța înainte.',
    },
    materiale_necesare: ['Tester priză', 'Priză de înlocuire', 'Șurubelnițe izolate'],
    cand_chemi_specialistul: 'OBLIGATORIU pentru orice intervenție în doze sau tablou electric.',
    embedding: [],
  },
  {
    id: 'el_003', categorie: 'electric',
    titlu: 'Bec sau lumină care pâlpâie',
    problema: 'Becul pâlpâie constant sau intermitent, fie el LED sau clasic.',
    cuvinte_cheie: ['bec', 'palpaie', 'led', 'lumina', 'intrerupator', 'contact', 'driver', 'condensator'],
    cauze_posibile: ['Driver LED defect sau de calitate slabă', 'Incompatibilitate LED cu dimmerul', 'Contact slab la dulie sau întrerupător'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '15-30 min',
      pasi: ['Încearcă un bec LED de brand cunoscut în loc', 'Dacă ai dimmer: asigură-te că becul e compatibil cu el', 'Verifică dullia — strânge contactele sau curăță de oxid', 'Dacă pâlpâie la pornire: verifică întrerupătorul'],
      sfat_pro: 'Beculețele ieftine de 5 lei au driver prost — un LED bun de 15 lei durează 10 ani.',
    },
    materiale_necesare: ['Bec LED calitate superioară', 'Dulie de înlocuire'],
    cand_chemi_specialistul: 'Dacă pâlpâie în toată casa — problemă de tensiune sau tablou.',
    embedding: [],
  },
  {
    id: 'el_004', categorie: 'electric',
    titlu: 'Întrerupător defect sau blocat',
    problema: 'Întrerupătorul de lumină nu mai face contact, e blocat sau spartat.',
    cuvinte_cheie: ['intrerupator', 'defect', 'blocat', 'contact', 'lumina', 'inlocuire', 'mecanism'],
    cauze_posibile: ['Mecanism de comutare uzat sau ars', 'Arc intern rupt sau contact oxidat'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '20-30 min',
      pasi: ['Oprește OBLIGATORIU curentul de la tablou (siguranța circuitului)', 'Testează cu testerul că nu e curent', 'Demontează rama și mecanismul (2 șuruburi)', 'Montează mecanismul nou cu aceleași conexiuni'],
      sfat_pro: 'Fotografiază conexiunile înainte de deconectare — e mai ușor la remontare.',
    },
    materiale_necesare: ['Întrerupător înlocuitor', 'Șurubelnițe izolate'],
    cand_chemi_specialistul: 'Oprește curentul de la tablou înainte — nicio excepție.',
    embedding: [],
  },
  {
    id: 'el_005', categorie: 'electric',
    titlu: 'Priză cu scântei sau miros de ars',
    problema: 'La introducerea ștecherului apar scântei sau se simte miros de plastic ars.',
    cuvinte_cheie: ['priza', 'scantei', 'miros', 'ars', 'pericol', 'incendiu', 'contact', 'oxid'],
    cauze_posibile: ['Contact electric deteriorat sau arc electric', 'Supraîncălzire din suprasarcină repetată'],
    solutie: {
      dificultate: 'URGENT', timp_estimat: 'Imediat',
      pasi: ['Deconectează imediat tot ce e conectat în acea priză', 'Oprește siguranța circuitului la tablou', 'Nu mai folosi priza — sigilează cu bandă de avertizare', 'Sună un electrician autorizat în aceeași zi'],
      sfat_pro: 'O priză cu scântei poate provoca incendiu în câteva ore. Nu amâna!',
    },
    materiale_necesare: ['Priză de înlocuire (montaj de electrician)'],
    cand_chemi_specialistul: 'OBLIGATORIU — risc imediat de incendiu și electrocutare.',
    embedding: [],
  },
  {
    id: 'el_006', categorie: 'electric',
    titlu: 'Cablu electric dezizolat sau deteriorat',
    problema: 'Se observă izolație ruptă, crăpată sau roasă pe un cablu electric din casă.',
    cuvinte_cheie: ['cablu', 'dezizolat', 'deteriorat', 'izolatie', 'rupt', 'pericol', 'banda'],
    cauze_posibile: ['Uzură mecanică prin treceri pe colțuri ascuțite', 'Rozătoare sau îmbătrânire izolație'],
    solutie: {
      dificultate: 'URGENT', timp_estimat: 'Imediat + înlocuire 1-4 ore',
      pasi: ['Oprește imediat curentul la acel circuit', 'Acoperă zona cu bandă electroizolantă ca măsură TEMPORARĂ', 'Măsoară lungimea cablului afectat', 'Înlocuiește COMPLET cablul — bandă = soluție de avarie'],
      sfat_pro: 'Bandă izolantă nu e soluție permanentă — agravează în timp. Înlocuiește cablul în max 48h.',
    },
    materiale_necesare: ['Bandă electroizolantă', 'Cablu înlocuitor', 'Cleme cablu'],
    cand_chemi_specialistul: 'OBLIGATORIU dacă e în pereți sau tablou electric.',
    embedding: [],
  },
  {
    id: 'el_007', categorie: 'electric',
    titlu: 'Tablou electric vechi cu siguranțe fuzibile',
    problema: 'Tabloul are siguranțe cu filet vechi, nu disjunctoare automate moderne.',
    cuvinte_cheie: ['tablou', 'sigurante', 'fuzibile', 'vechi', 'inlocuire', 'modernizare', 'disjunctor'],
    cauze_posibile: ['Instalație electrică veche (pre-1990)', 'Siguranțe adesea înlocuite cu valori prea mari — risc incendiu'],
    solutie: {
      dificultate: 'Avansat', timp_estimat: '4-8 ore',
      pasi: ['Solicită deviz de la electrician autorizat ANRE', 'Planifică lucrarea când poți sta fără curent o zi', 'Instalează tablou modern cu disjunctoare + diferențial 30mA', 'Verifică și refă conexiunile din tot apartamentul'],
      sfat_pro: 'Diferențialul de 30mA salvează vieți — include-l obligatoriu în tabloul nou.',
    },
    materiale_necesare: ['Tablou electric nou', 'Disjunctoare calibrate', 'Diferențial 30mA'],
    cand_chemi_specialistul: 'OBLIGATORIU — electrician autorizat ANRE.',
    embedding: [],
  },
  {
    id: 'el_008', categorie: 'electric',
    titlu: 'Lumina pâlpâie în toată casa',
    problema: 'Toate luminile din casă pâlpâie sau fluctuează tensiunea, mai ales seara.',
    cuvinte_cheie: ['lumina', 'palpaie', 'toata', 'casa', 'tensiune', 'fluctuatie', 'retea', 'bransament'],
    cauze_posibile: ['Problemă la rețeaua stradală a distribuitorului', 'Conexiune slabă la branșamentul blocului', 'Supraîncărcare rețea în zona respectivă'],
    solutie: {
      dificultate: 'Avansat', timp_estimat: 'Depinde de distribuitor',
      pasi: ['Măsoară tensiunea cu un multimetru la o priză (normal: 220-230V)', 'Verifică dacă și vecinii au aceeași problemă', 'Sună distribuitorul local de energie (Electrica/Enel/CEZ)', 'Raportează avaria cu adresa exactă'],
      sfat_pro: 'Nu e nimic de reparat în casă — e problemă la rețea. Reportul se face gratuit la distribuitor.',
    },
    materiale_necesare: [],
    cand_chemi_specialistul: 'Sună imediat distribuitorul local de energie electrică.',
    embedding: [],
  },
  {
    id: 'el_009', categorie: 'electric',
    titlu: 'LED-uri care se sting prematur',
    problema: 'Becurile LED se ard după câteva luni deși ar trebui să dureze ani.',
    cuvinte_cheie: ['led', 'sting', 'ard', 'prematur', 'driver', 'calitate', 'temperatura', 'supratensiune'],
    cauze_posibile: ['Becuri LED de calitate slabă cu driver defect', 'Temperatură prea mare în doze sau corpuri închise', 'Supratensiune în rețea'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '15 min',
      pasi: ['Înlocuiește cu LED-uri de brand recunoscut (Philips, Osram, Ledvance)', 'Verifică dacă corpul de iluminat permite ventilație suficientă', 'Verifică tensiunea rețelei la o priză', 'Montează stabilizator de tensiune dacă fluctuează'],
      sfat_pro: 'LED-urile ieftine de 3-5 lei au condensatori de proastă calitate care crapă rapid.',
    },
    materiale_necesare: ['LED-uri calitate superioară (brand recunoscut)'],
    cand_chemi_specialistul: 'Dacă se ard pe mai multe circuite simultan — problemă de tensiune în rețea.',
    embedding: [],
  },
  {
    id: 'el_010', categorie: 'electric',
    titlu: 'Priză de exterior defectă sau infiltrată de apă',
    problema: 'Priza din exterior nu funcționează sau prezintă urme de oxidare și umezeală.',
    cuvinte_cheie: ['priza', 'exterior', 'apa', 'umiditate', 'oxidare', 'ip44', 'etansa', 'umeda'],
    cauze_posibile: ['Carcasă neadecvată pentru exterior', 'Infiltrație de apă prin neetanșeități', 'Oxid pe contacte din expunere la intemperii'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '30-60 min',
      pasi: ['Oprește curentul la tablou', 'Demontează priza veche și usucă bine zona', 'Curăță conexiunile de oxid cu hârtie abrazivă fină', 'Montează priză IP44 (sau IP65 pentru expunere directă la ploaie)'],
      sfat_pro: 'IP44 = protecție la stropi. IP65 = protecție la jet de apă. Alege în funcție de locul de montaj.',
    },
    materiale_necesare: ['Priză exterior IP44', 'Carcasă etanșă', 'Silicon exterior'],
    cand_chemi_specialistul: 'Oprește curentul la tablou înainte de orice intervenție.',
    embedding: [],
  },
  {
    id: 'el_011', categorie: 'electric',
    titlu: 'Detector de fum care bip-uiește constant',
    problema: 'Detectorul de fum emite beep-uri intermitente fără motiv aparent.',
    cuvinte_cheie: ['detector', 'fum', 'alarma', 'bip', 'baterie', 'test', 'praf'],
    cauze_posibile: ['Baterie descărcată (cel mai comun)', 'Praf sau insecte în camera de detecție', 'Detector vechi (durata de viață ~10 ani)'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '5 min',
      pasi: ['Identifică detectorul care bipa', 'Înlocuiește bateria 9V (durata normală: 1 an)', 'Curăță cu aer comprimat sau aspirator camera de detecție', 'Testează cu butonul Test'],
      sfat_pro: 'Schimbă bateria la toți detectoarele o dată pe an, de exemplu la schimbarea orei.',
    },
    materiale_necesare: ['Baterie 9V'],
    cand_chemi_specialistul: 'Nu e necesar — operațiune simplă.',
    embedding: [],
  },
  {
    id: 'el_012', categorie: 'electric',
    titlu: 'Termostat programabil nu funcționează',
    problema: 'Termostatul nu pornește/oprește centrala la temperaturile setate.',
    cuvinte_cheie: ['termostat', 'programabil', 'centrala', 'temperatura', 'setare', 'baterie', 'calibrare'],
    cauze_posibile: ['Baterii descărcate', 'Setare incorectă sau corupere program', 'Cablaj de control defect'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '20-30 min',
      pasi: ['Înlocuiește bateriile AA sau AAA', 'Resetează la setările din fabrică (buton reset sau scoate bateriile 30s)', 'Reconfigurează programul și temperatura', 'Dacă tot nu merge: verifică cablajul 2-3 fire de control'],
      sfat_pro: 'Citește manualul pentru codul de eroare afișat — îți spune exact problema.',
    },
    materiale_necesare: ['Baterii AA', 'Manual termostat'],
    cand_chemi_specialistul: 'Dacă după resetare tot nu funcționează — defect intern, înlocuiește termostatul.',
    embedding: [],
  },
  {
    id: 'el_013', categorie: 'electric',
    titlu: 'Cablu prelungitor supraîncălzit',
    problema: 'Cablul prelungitor sau bara de prize devine fierbinte la atingere.',
    cuvinte_cheie: ['prelungitor', 'bara', 'prize', 'supraincalzit', 'fierbinte', 'suprasarcina', 'pericol'],
    cauze_posibile: ['Prea mulți consumatori de putere mare pe același prelungitor', 'Secțiunea cablului prea mică pentru consumul solicitat'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '5 min',
      pasi: ['Deconectează imediat prelungitorul', 'Calculează wattajul total (suma aparatelor conectate)', 'Înlocuiește cu prelungitor cu secțiunea 3×1.5mm² sau 3×2.5mm²', 'Redistribuie aparatele mari (fier de călcat, microunde) pe prize directe'],
      sfat_pro: 'Niciodată aparate de gătit sau de 2000W+ pe prelungitor — acestea merg direct la priză.',
    },
    materiale_necesare: ['Prelungitor cu secțiune 3×1.5mm² sau mai mare'],
    cand_chemi_specialistul: 'Dacă prelungitorul miroase a ars — aruncă-l imediat, nu-l repara.',
    embedding: [],
  },
  {
    id: 'el_014', categorie: 'electric',
    titlu: 'Centrală termică nu pornește',
    problema: 'Centrala de apartament nu pornește sau afișează cod de eroare.',
    cuvinte_cheie: ['centrala', 'termica', 'porneste', 'eroare', 'cod', 'presiune', 'gaz', 'resetare'],
    cauze_posibile: ['Presiunea apei prea mică (sub 1 bar)', 'Cod de eroare specific (supraîncălzire, presiune, ionizare)', 'Termostat de cameră deconectat sau baterie descărcată'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '15-30 min',
      pasi: ['Verifică manometrul centralei — trebuie să fie 1.5-2 bar', 'Dacă e sub 1 bar: deschide robinetul de umplere până la 1.5 bar', 'Apasă butonul Reset și așteaptă 30s', 'Citește codul de eroare în manual și urmează instrucțiunile'],
      sfat_pro: 'Fotografiază codul de eroare de pe display — ajută tehnicianul să diagnosticheze rapid.',
    },
    materiale_necesare: ['Manual centrală'],
    cand_chemi_specialistul: 'OBLIGATORIU pentru intervenții la gaz sau interiorul centralei.',
    embedding: [],
  },
  {
    id: 'el_015', categorie: 'electric',
    titlu: 'Sonerie sau interfon defect',
    problema: 'Soneria de ușă sau interfonul nu mai funcționează, nu sună sau nu se aude.',
    cuvinte_cheie: ['sonerie', 'interfon', 'defect', 'suna', 'transformator', 'buton', 'cablu'],
    cauze_posibile: ['Buton de sonerie cu contact oxidat', 'Transformator defect', 'Cablu bifilat întrerupt'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-40 min',
      pasi: ['Testează butonul exterior cu un tester de continuitate', 'Verifică transformatorul — trebuie să dea 8-12V AC', 'Trasează cablul de la buton la sonerie', 'Înlocuiește componenta defectă'],
      sfat_pro: 'Butoanele de sonerie se oxidează în 5-7 ani. Înlocuire: sub 15 RON și 10 minute.',
    },
    materiale_necesare: ['Buton sonerie', 'Transformator 8V', 'Cablu bifilat'],
    cand_chemi_specialistul: 'Nu e necesar pentru sonerie simplă.',
    embedding: [],
  },

  // ── CONSTRUCȚII ─────────────────────────────────────────────────────────────

  {
    id: 'con_001', categorie: 'constructii',
    titlu: 'Fisuri în perete de apartament',
    problema: 'Au apărut fisuri pe peretele interior, fie orizontale, fie verticale sau diagonale.',
    cuvinte_cheie: ['fisuri', 'perete', 'crapaturi', 'tencuiala', 'structural', 'umiditate', 'tasare'],
    cauze_posibile: ['Tasare normală a clădirii (fisuri fine, superficiale)', 'Problemă structurală sau de fundație (fisuri late și active)'],
    solutie: {
      dificultate: 'Ușor-Avansat', timp_estimat: '1-8 ore',
      pasi: ['Evaluează lățimea: sub 1mm = superficială, peste 5mm = structurală', 'Largește ușor fisura cu spaclu și curăță praful', 'Umple cu chit pentru fisuri + aplică bandă de armare', 'Gletuiește, lasă să se usuce și vopsește'],
      sfat_pro: 'Marchează capetele fisurii cu creion și data — dacă crește în 30 de zile, cheamă inginerul.',
    },
    materiale_necesare: ['Chit fisuri', 'Bandă armatură', 'Vopsea lavabilă'],
    cand_chemi_specialistul: 'Dacă fisura e mai lată de 5mm, activă sau diagonală la 45° — inginer structurist.',
    embedding: [],
  },
  {
    id: 'con_002', categorie: 'constructii',
    titlu: 'Igrasie și umezeală pe pereți',
    problema: 'Pete de umezeală sau mucegai pe pereți, mai ales în colțuri și la baza pereților.',
    cuvinte_cheie: ['igrasie', 'umiditate', 'mucegai', 'pete', 'perete', 'condensare', 'izolatie', 'infiltratie'],
    cauze_posibile: ['Condens din cauza izolației termice slabe', 'Infiltrație de apă din exterior sau de la vecini', 'Ventilație insuficientă a încăperii'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '2-8 ore',
      pasi: ['Identifică sursa: condens (perete rece) sau infiltrație (apa vine din afară)', 'Tratează mucegaiul cu soluție antimucegai pe bază de clor', 'Aplică grundant hidrofug și vopsea cu biocid', 'Îmbunătățește ventilația (grilă ventilație sau aerisire zilnică)'],
      sfat_pro: 'Umiditatea relativă ideală în casă e 40-60%. Higrometrul costă 20 RON și te ajută să monitorizezi.',
    },
    materiale_necesare: ['Soluție antimucegai', 'Vopsea hidrofugă', 'Grund izolant'],
    cand_chemi_specialistul: 'Dacă vine din exteriorul clădirii sau din fundație — tratament de termoizolație.',
    embedding: [],
  },
  {
    id: 'con_003', categorie: 'constructii',
    titlu: 'Tencuială care se desface de pe perete',
    problema: 'Tencuiala se umflă, crapă și cade în bucăți de pe perete sau tavan.',
    cuvinte_cheie: ['tencuiala', 'cade', 'desface', 'perete', 'tavan', 'reparatie', 'amorsa', 'grund'],
    cauze_posibile: ['Umezeală în substrat care a desprins tencuiala', 'Aderență slabă din aplicare incorectă inițial'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '4-8 ore + uscare',
      pasi: ['Înlătură tot ce e slab cu ciocanul și dalta (bate ușor, scoate bucăți mici)', 'Curăță suprafața de praf și amorsează cu grund de contact', 'Aplică mortar de reparații în 2-3 straturi subțiri, nu unul gros', 'Finisează cu glet și vopsea'],
      sfat_pro: 'Fiecare strat de mortar trebuie să se usuce complet înainte de următorul — nu te grăbi.',
    },
    materiale_necesare: ['Mortar reparații', 'Grund contact', 'Glet finisaj'],
    cand_chemi_specialistul: 'Dacă tencuiala cade pe suprafețe mari de tavan — risc de accidentare.',
    embedding: [],
  },
  {
    id: 'con_004', categorie: 'constructii',
    titlu: 'Gresie sau faianță care se desprinde',
    problema: 'Plăci de gresie sau faianță s-au desprins de pe podea sau perete.',
    cuvinte_cheie: ['gresie', 'faianta', 'desprins', 'lipire', 'adeziv', 'rost', 'inlocuire', 'placi'],
    cauze_posibile: ['Adeziv vechi care a cedat', 'Substrat umed sau flexibil sub plăci', 'Dilatare termică fără rosturi de dilataresuficiente'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '2-4 ore + 24h uscare',
      pasi: ['Curăță bine substratul de adezivul vechi cu dalta', 'Aplică adeziv flex C2 uniform cu spatula dințată', 'Pozitionează placa și verifică cu nivela cu bulă', 'Refă rosturile cu chit de rost după 24h'],
      sfat_pro: 'Adezivul Flex (C2) e indispensabil în baie sau bucătărie — rezistă la umezeală și mișcări.',
    },
    materiale_necesare: ['Adeziv flex C2 gresie', 'Chit rost', 'Spatulă dințată'],
    cand_chemi_specialistul: 'Dacă se desprind în masă — posibil substrat compromis de umezeală.',
    embedding: [],
  },
  {
    id: 'con_005', categorie: 'constructii',
    titlu: 'Parchet care scârțâie la mers',
    problema: 'Parchetul scoate zgomote de scârțâit când mergi pe el, mai ales în anumite zone.',
    cuvinte_cheie: ['parchet', 'scartiie', 'scartait', 'podea', 'lemn', 'sapa', 'lipire', 'dilatare'],
    cauze_posibile: ['Lamele care frecă una de alta din cauza lipsei rostului de dilatatare', 'Lipire insuficientă la substrat în zone localizate'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '2-4 ore',
      pasi: ['Identifică lamelele problema — parcurge-le și marchează cu bandă', 'Injectează adeziv PVA diluat cu seringa prin crăpăturile fine', 'Apasă cu greutăți sau clame 24h', 'Fixează cu șuruburi speciale invizibile dacă persistă'],
      sfat_pro: 'Umezeala excesivă sau lipsa umidificatorului iarna cauzează contracție și scârțâit — verifică umiditatea.',
    },
    materiale_necesare: ['Adeziv parchet', 'Șuruburi speciale parchet', 'Putty lemn'],
    cand_chemi_specialistul: 'Dacă întreaga suprafață scârțâie — posibil substrat compromis.',
    embedding: [],
  },
  {
    id: 'con_006', categorie: 'constructii',
    titlu: 'Fereastră care nu se închide etanș',
    problema: 'Fereastra lasă aer rece să intre, se simte curent sau condenul apare pe rama interioară.',
    cuvinte_cheie: ['fereastra', 'garnitura', 'etansare', 'curent', 'aer', 'reglare', 'balamale', 'pvc'],
    cauze_posibile: ['Garnitură perimetrală uzată sau crăpată', 'Balamale și calacane nereglate — presiune insuficientă'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30-60 min',
      pasi: ['Testează cu o foaie de hârtie — dacă iese ușor, garnitura e slabă', 'Înlocuiește garnitura perimetrală (se scoate din canal și se pune alta)', 'Reglează balamalele cu cheia hex (sus-jos și adâncime)', 'Testează etanșarea cu hârtia din nou'],
      sfat_pro: 'Reglajul ferestrei PVC se face gratuit de instalator în garanție — verifică dacă mai ești în garanție.',
    },
    materiale_necesare: ['Garnitură fereastră PVC', 'Spray lubrifiant balamale'],
    cand_chemi_specialistul: 'Dacă rama e deformată sau geamul e fisurat.',
    embedding: [],
  },
  {
    id: 'con_007', categorie: 'constructii',
    titlu: 'Ușă de interior care atârnă sau nu se închide',
    problema: 'Ușa se lovește de tocul ușii, nu se închide complet sau se deschide singură.',
    cuvinte_cheie: ['usa', 'atarna', 'inchide', 'balamale', 'reglare', 'toc', 'balanta', 'frecare'],
    cauze_posibile: ['Balamale slăbite din șuruburi care s-au deșurupat', 'Balamale nereglate (la cele moderne cu reglaj 3D)'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '15-30 min',
      pasi: ['Strânge șuruburile balamalei — verifică mai întâi asta', 'Dacă balamalele sunt moderne: reglează sus-jos, stânga-dreapta, adâncime cu cheia hex', 'Testează închiderea pe tot conturul', 'Lubrifie mecanismul și broasca'],
      sfat_pro: 'Balamalele cu reglaj 3D permit ajustare fără demontare — caută șuruburile hex de pe fiecare balama.',
    },
    materiale_necesare: ['Cheie hex', 'Șuruburi inox', 'Spray lubrifiant'],
    cand_chemi_specialistul: 'Dacă tocul ușii e deformat sau pereții s-au mișcat (structural).',
    embedding: [],
  },
  {
    id: 'con_008', categorie: 'constructii',
    titlu: 'Tavan cu pete de umezeală de la vecin',
    problema: 'Pete maronii sau galbene au apărut pe tavan, posibil infiltrație de la etajul superior.',
    cuvinte_cheie: ['tavan', 'pete', 'umezeala', 'infiltratie', 'vecin', 'scurgere', 'reparatie'],
    cauze_posibile: ['Scurgere de la vecin de deasupra (robinet, WC, instalație)', 'Hidroizolație defectă la baia etajului superior'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '4-8 ore + 48h uscare',
      pasi: ['Identifică și oprește sursa (discuță cu vecinul de deasupra)', 'Lasă tavanul să se usuce COMPLET — minim 48-72h', 'Aplică grundant hidrofug pe petele de umezeală', 'Revopsește cu vopsea de plafon (2 straturi)'],
      sfat_pro: 'Nu vopsi peste umezeală activă — vopseaua pică în câteva săptămâni. Uscarea e totul.',
    },
    materiale_necesare: ['Grund hidrofug', 'Vopsea plafon', 'Chit reparații'],
    cand_chemi_specialistul: 'Dacă structura tavanului e afectată sau picură activ.',
    embedding: [],
  },
  {
    id: 'con_009', categorie: 'constructii',
    titlu: 'Podea de beton crăpată în garaj sau subsol',
    problema: 'Betonul de pe podea are fisuri, se fărâmițează sau are porțiuni denivelate.',
    cuvinte_cheie: ['beton', 'podea', 'fisura', 'crapata', 'garaj', 'subsol', 'mortar', 'epoxidic'],
    cauze_posibile: ['Îmbătrânire și contracție beton', 'Presiune de la sol sau fundație'],
    solutie: {
      dificultate: 'Mediu-Avansat', timp_estimat: '4-16 ore',
      pasi: ['Curăță fisura de praf și materiale slabe cu peria de sârmă', 'Amorsează cu grundant penetrant pentru beton', 'Umple cu mortar epoxidic fluid (curgerea singur în fisură)', 'Lasă 24h și verifică — repetă dacă e necesar'],
      sfat_pro: 'Mortarul epoxidic e mult mai rezistent decât betonul normal — o reparație bună durează 10+ ani.',
    },
    materiale_necesare: ['Mortar epoxidic', 'Grundant penetrant beton', 'Amorsa beton'],
    cand_chemi_specialistul: 'Dacă fisurile sunt structurale (fundație) — inginer de structuri obligatoriu.',
    embedding: [],
  },
  {
    id: 'con_010', categorie: 'constructii',
    titlu: 'Izolație termică insuficientă — perete rece',
    problema: 'Peretele exterior e rece iarna, condensul apare pe interior, facturile la energie sunt mari.',
    cuvinte_cheie: ['izolatie', 'termica', 'perete', 'rece', 'condensat', 'polistiren', 'vata', 'termoizolatie'],
    cauze_posibile: ['Lipsă totală sau parțială de termoizolație exterioară', 'Pod termic la anveloparea blocului'],
    solutie: {
      dificultate: 'Avansat', timp_estimat: 'Câteva zile',
      pasi: ['Măsoară temperatura peretelui cu termometru infraroșu — sub 14°C înseamnă problemă', 'Decide: izolație exterioară (polistiren) sau interioară (vată+gips-carton)', 'Termoizolația exterioară e mai eficientă dar necesită asociație de proprietari', 'Soluție rapidă interior: lambriu termoizolant sau gips-carton cu vată minerală 5-10cm'],
      sfat_pro: 'Termoizolația interioară sacrifică 10-15cm din cameră dar poate fi făcută singur fără asociație.',
    },
    materiale_necesare: ['Polistiren EPS 10cm', 'Adeziv termoizolant', 'Tencuială armată'],
    cand_chemi_specialistul: 'Recomandabil pentru lucrări de termoizolație exterioară.',
    embedding: [],
  },
  {
    id: 'con_011', categorie: 'constructii',
    titlu: 'Scări interioare care scârțâie',
    problema: 'Treptele de lemn ale scărilor interioare fac zgomot la urcat sau coborât.',
    cuvinte_cheie: ['scari', 'trepte', 'scartiie', 'lemn', 'fixare', 'suruburi', 'adeziv', 'podea'],
    cauze_posibile: ['Îmbinări slăbite din mișcări repetate', 'Contracție a lemnului din lipsă de umiditate'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '2-4 ore',
      pasi: ['Identifică treptele problema mergând pe fiecare', 'Din subsol sau de dedesubt: injectează adeziv PVA la îmbinări', 'Fixează treptele cu șuruburi din unghi (prin contratoaptă în toaptă)', 'Umple golurile cu pastă de lemn și finisează'],
      sfat_pro: 'Lubrifianții (talc, spray silicon) sunt soluție temporară. Adezivul e permanent.',
    },
    materiale_necesare: ['Șuruburi inox', 'Adeziv lemn PVA', 'Putty lemn'],
    cand_chemi_specialistul: 'Dacă structura portantă a scărilor (grinzile) e afectată.',
    embedding: [],
  },
  {
    id: 'con_012', categorie: 'constructii',
    titlu: 'Perete de gips-carton cu găuri sau deteriorat',
    problema: 'Peretele fals din gips-carton are găuri, lovituri sau porțiuni umede.',
    cuvinte_cheie: ['gips', 'carton', 'gaura', 'deteriorat', 'placa', 'inlocuire', 'chit', 'spaclu'],
    cauze_posibile: ['Impact mecanic', 'Umezeală din infiltrație sau condensare'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '1-4 ore',
      pasi: ['Gauri mici (sub 5cm): aplică chit de gips + bandă de armare', 'Găuri mari: taie un patch pătrat, fixează cu cleme speciale sau șipci', 'Chituiește suprafața în 2 straturi', 'Glăsuiește și vopsește'],
      sfat_pro: 'Găuri mici reparate bine dispar complet sub vopsea. Cheia e șlefuirea fină între straturi.',
    },
    materiale_necesare: ['Chit gips', 'Bandă armatură', 'Patch gips-carton'],
    cand_chemi_specialistul: 'Nu e necesar pentru reparații mici.',
    embedding: [],
  },
  {
    id: 'con_013', categorie: 'constructii',
    titlu: 'Balcon cu infiltrații de apă',
    problema: 'Apa de ploaie intră pe balcon sau terasă și ajunge pe podea sau perete interior.',
    cuvinte_cheie: ['balcon', 'terasa', 'infiltratie', 'apa', 'ploaie', 'hidroizolatie', 'panta', 'scurgere'],
    cauze_posibile: ['Hidroizolație degradată sau lipsa ei', 'Pantă insuficientă spre scurgere', 'Scurgere înfundată'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '4-8 ore + 48h uscare',
      pasi: ['Curăță și degresează suprafața balconului', 'Curăță scurgerea de frunze și mizerie', 'Aplică membrană hidroizolantă elastică în 2 straturi (la 4h interval)', 'Verifică la proxima ploaie'],
      sfat_pro: 'Hidroizolația se suie obligatoriu pe perete 15-20cm — acolo sunt 90% din infiltrații.',
    },
    materiale_necesare: ['Membrană hidroizolantă elastică', 'Mortar hidroizolant', 'Grund'],
    cand_chemi_specialistul: 'Dacă structura balconului (betonul armat) are fisuri sau coroziune.',
    embedding: [],
  },
  {
    id: 'con_014', categorie: 'constructii',
    titlu: 'Vopsea care se coajă de pe pereți',
    problema: 'Vopseaua de pe pereți sau tavan se coajă, bășicuiește sau cade în fâșii.',
    cuvinte_cheie: ['vopsea', 'coaja', 'basicuieste', 'cade', 'perete', 'tavan', 'umiditate', 'grund'],
    cauze_posibile: ['Perete umed sau vopsit fără grund pe suprafață poroasă', 'Incompatibilitate între straturile de vopsea veche și nouă'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '4-8 ore',
      pasi: ['Îndepărtează TOT ce se coajă — cu racleta sau gletiera lată', 'Verifică peretele pentru umezeală (dacă e umed, rezolvă asta mai întâi)', 'Amorsează cu grund penetrant', 'Vopsește cu 2 straturi de vopsea lavabilă de calitate'],
      sfat_pro: 'Grundul nu e opțional — e diferența dintre vopsea care ține 10 ani și una care pică în 1 an.',
    },
    materiale_necesare: ['Grund izolant', 'Vopsea lavabilă de calitate', 'Glet finisaj'],
    cand_chemi_specialistul: 'Dacă vine din probleme de umezeală — rezolvă mai întâi cauza.',
    embedding: [],
  },
  {
    id: 'con_015', categorie: 'constructii',
    titlu: 'Ușă exterior care lasă curenți de aer',
    problema: 'Ușa de intrare în apartament sau casă are spații pe lângă toc prin care intră aer rece.',
    cuvinte_cheie: ['usa', 'exterior', 'curent', 'aer', 'garnitura', 'prag', 'etansare', 'baie'],
    cauze_posibile: ['Garnitură perimetrală uzată sau lipsă', 'Prag de jos fără burete sau periuță de etanșare'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '30-60 min',
      pasi: ['Testează cu lumânare — dacă flacăra tremură, ai infiltrație', 'Montează garnitură autoadezivă pe tot perimetrul tocului', 'Montează prag cu burete sau periuță la baza ușii', 'Testează din nou cu lumânarea'],
      sfat_pro: 'Etanșarea ușii de intrare reduce factura la căldură cu 10-15% — investiție de 50 RON, câștig de 200+ RON/an.',
    },
    materiale_necesare: ['Garnitură autoadezivă', 'Prag etanșare', 'Silicon transparent'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },

  // ── MOBILĂ ──────────────────────────────────────────────────────────────────

  {
    id: 'mob_001', categorie: 'mobila',
    titlu: 'Ușă de dulap care nu se închide aliniat',
    problema: 'Ușa dulapului nu se aliniază cu cealaltă ușă, lasă spațiu inegal sau se deschide singură.',
    cuvinte_cheie: ['usa', 'dulap', 'balamale', 'reglare', 'inchide', 'aliniere', 'hex', 'ajustare'],
    cauze_posibile: ['Balamale moderne dezreglate în timp', 'Corpul dulapului ușor deformat din greutate'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '10-15 min',
      pasi: ['Localizează cei 3 șuruburi hex de pe fiecare balama', 'Șurub lateral: alinierea stânga-dreapta', 'Șurub central: adâncimea față de corp', 'Șurub vertical (dacă există): sus-jos'],
      sfat_pro: 'Reglează câte 1/4 de tură la fiecare șurub și testează — nu exagera cu reglajul.',
    },
    materiale_necesare: ['Cheie hex 2-4mm'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_002', categorie: 'mobila',
    titlu: 'Sertar blocat sau care iese din șine',
    problema: 'Sertarul nu se mai trage ușor, e blocat sau iese complet din glisierele lui.',
    cuvinte_cheie: ['sertar', 'blocat', 'sina', 'glisiera', 'iese', 'lubrifiere', 'reglare', 'montaj'],
    cauze_posibile: ['Șine murdare sau uscate de lubrifiant', 'Șine dezaliniate sau șuruburi slăbite'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '15-30 min',
      pasi: ['Extrage complet sertarul', 'Curăță șinele cu cârpă umedă', 'Lubrifie cu ceară de lumânare sau spray silicon', 'Verifică alinierea șinelor și strânge șuruburile'],
      sfat_pro: 'Ceara de lumânare e la fel de bună ca spray-ul silicon și costă 0.',
    },
    materiale_necesare: ['Spray silicon', 'Ceară lumânare', 'Șurubelniță'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_003', categorie: 'mobila',
    titlu: 'Scaun cu picioare slabe sau care se clatină',
    problema: 'Scaunul se clatină, picioarele s-au slăbit din îmbinări sau unul e mai scurt.',
    cuvinte_cheie: ['scaun', 'clatina', 'picior', 'imbinare', 'adeziv', 'surub', 'ranfort', 'consolidare'],
    cauze_posibile: ['Adeziv original uscat și deteriorat din vârstă', 'Îmbinări cu lemn expandat din umezeală și contractat'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '1 oră + 4h uscare',
      pasi: ['Demontează complet piciorul slăbit', 'Curăță adezivul vechi cu hârtie abrazivă', 'Aplică adeziv PVA generos la îmbinare', 'Strânge cu colier de mobilă 4h — nu te așeza pe el înainte'],
      sfat_pro: 'Adezivul PVA în îmbinările de lemn e mai rezistent decât lemnul în sine dacă e aplicat corect.',
    },
    materiale_necesare: ['Adeziv PVA', 'Colier strângere mobilă', 'Pene lemn'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_004', categorie: 'mobila',
    titlu: 'Suprafață masă sau birou zgâriată sau deteriorată',
    problema: 'Blatul mesei are zgârieturi adânci, pete sau finisajul s-a deteriorat.',
    cuvinte_cheie: ['masa', 'birou', 'balt', 'zgarietura', 'deteriorat', 'finisaj', 'reparatie', 'ulei', 'lac'],
    cauze_posibile: ['Impact mecanic sau uzură zilnică', 'Umezeală sau căldură care a afectat lemnul sau folierea'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '30 min - 4 ore',
      pasi: ['Zgârieturi superficiale: aplică ceară de mobilă sau marker lemn de aceeași culoare', 'Zgârieturi adânci: șlefuiește cu hârtie abrazivă 120, apoi 220', 'Aplică ulei de lemn sau lac pe zona șlefuită', 'Finisează cu același produs ca restul suprafeței'],
      sfat_pro: 'Testează culoarea markerului pe o zonă ascunsă — nu există niciodată o potrivire perfectă.',
    },
    materiale_necesare: ['Ceară mobilă', 'Marker lemn', 'Lac mobilă', 'Hârtie șmirghel'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_005', categorie: 'mobila',
    titlu: 'Pat cu șine de susținere rupte',
    problema: 'Șinele de lemn sau metal care susțin salteaua s-au rupt sau au ieșit din locaș.',
    cuvinte_cheie: ['pat', 'sina', 'lamela', 'rupe', 'sparge', 'saltea', 'inlocuire', 'sustinere'],
    cauze_posibile: ['Suprasolicitare sau slabă calitate a lamelelor', 'Lemn uscat și fisurat din cauza timpului'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '10-20 min',
      pasi: ['Identifică lamela ruptă și măsoară-i lățimea (standard 63mm)', 'Cumpără lamele de înlocuire din lemn de fag', 'Scoate lamela ruptă și pune-o pe cea nouă în suporți', 'Verifică că nu clatină'],
      sfat_pro: 'Lamelele de înlocuire se găsesc la IKEA sau magazinele de mobilă — sub 20 RON bucata.',
    },
    materiale_necesare: ['Lamele pat înlocuitor'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_006', categorie: 'mobila',
    titlu: 'Bibliotecă sau raft care se încovoaie',
    problema: 'Polița bibliotecii sau raftul s-a încovoiat sub greutatea cărților.',
    cuvinte_cheie: ['raft', 'biblioteca', 'incovoia', 'sageat', 'greutate', 'suport', 'consolidare', 'lemn'],
    cauze_posibile: ['PAL de grosime insuficientă pentru deschiderea raftului', 'Greutate prea mare distribuită neuniform'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30-60 min',
      pasi: ['Golește raftul de cărți', 'Adaugă o consolă de susținere metalică în centrul raftului', 'Sau înlocuiește PAL-ul de 16mm cu lemn masiv sau PAL 25mm', 'Redistribuie greutatea uniform după montaj'],
      sfat_pro: 'Regula generală: raft de 16mm PAL suportă greutate fără încovoiere pe max 80cm deschidere.',
    },
    materiale_necesare: ['Consolă metalică intermediară', 'Șuruburi', 'Placă PAL 25mm'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_007', categorie: 'mobila',
    titlu: 'Mâner de ușă sau sertar care s-a desprins',
    problema: 'Mânerul s-a rupt, șurubul s-a deșurupat sau mânerul e deteriorat.',
    cuvinte_cheie: ['maner', 'rupe', 'desprins', 'surub', 'inlocuire', 'usa', 'sertar', 'prindere'],
    cauze_posibile: ['Șurub slăbit din utilizare repetată', 'Gaura în PAL lărgită (PAL-ul s-a desprins)'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '5-10 min',
      pasi: ['Verifică șurubul din interior (pe dos) — poate e doar slăbit', 'Strânge șurubul cu șurubelnița', 'Dacă gaura e lărgită: umple cu dopuri de lemn cu adeziv, lasă să se usuce și reșurubează', 'Înlocuiește mânerul dacă e rupt (verifică distanța dintre găuri)'],
      sfat_pro: 'Fotografiază mânerul vechi și măsoară distanța dintre găuri înainte de a cumpăra altul.',
    },
    materiale_necesare: ['Mâner înlocuitor', 'Șuruburi M4'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_008', categorie: 'mobila',
    titlu: 'Balamale uzate la dulap sau ușă mobilă',
    problema: 'Balamalele scârțâie, au joc exagerat sau mecanismul de amortizare nu mai funcționează.',
    cuvinte_cheie: ['balamale', 'uzate', 'scartiie', 'amortizare', 'slow', 'close', 'inlocuire', 'fixare'],
    cauze_posibile: ['Amortizorul hidraulic intern s-a defectat', 'Joc excesiv din uzura mecanică a balamalei'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '10-20 min',
      pasi: ['Dacă scârțâie: lubrifie axa balamalei cu WD-40', 'Dacă amortizorul nu funcționează: înlocuiește balama identică', 'Măsoară diametrul cupei: 26mm sau 35mm (standard european)', 'Montează balamalele noi în găurile existente'],
      sfat_pro: 'Balamalele cu soft-close se găsesc la 8-15 RON bucata — merită înlocuirea celor vechi.',
    },
    materiale_necesare: ['Balamale înlocuitor', 'WD-40', 'Cheie hex'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_009', categorie: 'mobila',
    titlu: 'Canapea sau fotoliu cu resort rupt',
    problema: 'Canapeaua are o porțiune moale care cedează, resort rupt sau pernă tasată.',
    cuvinte_cheie: ['canapea', 'fotoliu', 'resort', 'rupt', 'cedeza', 'tasata', 'perna', 'spuma', 'tapiterie'],
    cauze_posibile: ['Resort tip S sau sinuos rupt din suprasolicitare', 'Spumă poliuretanică degradată din vârstă'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '1-3 ore',
      pasi: ['Întoarce canapeaua și examinează resoartele prin pânza de dedesubt', 'Localizează resortul rupt (nu mai e tensionat)', 'Înlocuiește cu resort de tip S similar', 'Soluție rapidă alternativă: placă de placaj 12mm sub pernă'],
      sfat_pro: 'Resorturile de tip S costă 5-10 RON bucata și se găsesc la tapițeri sau online.',
    },
    materiale_necesare: ['Resort tip S înlocuitor', 'Placă placaj 12mm', 'Spumă poliuretanică'],
    cand_chemi_specialistul: 'Pentru retapițare completă — tapițer profesionist.',
    embedding: [],
  },
  {
    id: 'mob_010', categorie: 'mobila',
    titlu: 'Masă de sufragerie cu picioare inegale',
    problema: 'Masa se clatină pentru că un picior e mai scurt sau podeaua e inegală.',
    cuvinte_cheie: ['masa', 'clatina', 'picior', 'inegal', 'nivelat', 'pana', 'talpa', 'reglabil'],
    cauze_posibile: ['Podea denivelată', 'Talpă uzată inegal sau picior mai scurt din fabricație'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '10-15 min',
      pasi: ['Verifică care picior e scurt cu o riglă sau boloboc', 'Montează tălpi reglabile înfiletate sub fiecare picior', 'Reglează piciorul scurt până masa stă stabilă', 'Testează împingând dintr-o parte'],
      sfat_pro: 'Tălpile reglabile costă 10-15 RON setul și rezolvă definitiv orice masă care se clatină.',
    },
    materiale_necesare: ['Tălpi reglabile înfiletate', 'Pene autoadezive'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_011', categorie: 'mobila',
    titlu: 'Dulap care nu stă drept sau e instabil',
    problema: 'Dulapul mare e înclinat, se clatină sau amenință să cadă.',
    cuvinte_cheie: ['dulap', 'inclinat', 'instabil', 'clatina', 'ancorare', 'perete', 'siguranta', 'nivel'],
    cauze_posibile: ['Podea denivelată sau picioare nereglate', 'Nelipkit de perete — risc de răsturnare'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '30-60 min',
      pasi: ['Reglează picioarele până dulapul e drept (boloboc)', 'Fixează OBLIGATORIU cu colțare metalice în perete', 'Dibluri adecvate tipului de perete (BCA, cărămidă, gips-carton)', 'Verifică stabilitatea trăgând ușor din partea de sus'],
      sfat_pro: 'OBLIGATORIU ancorat în perete dacă există copii în casă — riscul de răsturnare e real.',
    },
    materiale_necesare: ['Colțare ancorare', 'Dibluri perete', 'Boloboc'],
    cand_chemi_specialistul: 'Nu e necesar dacă urmezi pașii. Ancorarea e obligatorie.',
    embedding: [],
  },
  {
    id: 'mob_012', categorie: 'mobila',
    titlu: 'Tapițerie ruptă la scaun sau canapea',
    problema: 'Stofa sau pielea scaunului/canapelei s-a rupt, s-a decolorat sau se deteriorează.',
    cuvinte_cheie: ['tapiterie', 'rupe', 'stofa', 'piele', 'reparatie', 'acoperire', 'husa'],
    cauze_posibile: ['Uzură mecanică repetată în zone de contact', 'Expunere la soare sau produse chimice'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '30 min - 2 ore',
      pasi: ['Soluție rapidă: husă universală de calitate potrivită dimensiunii', 'Reparație piele: patch autoadeziv de piele sau adeziv pentru piele', 'Reparație stofă: plasture de stofă similar cusut sau lipit', 'Soluție definitivă: tapițer profesionist'],
      sfat_pro: 'Husele de calitate de 100-200 RON prelungesc viața canapelei cu 5-10 ani.',
    },
    materiale_necesare: ['Husă universală', 'Adeziv tapițerie', 'Material tapițerie'],
    cand_chemi_specialistul: 'Tapițer pentru lucrări de calitate — merită pentru piese de valoare.',
    embedding: [],
  },
  {
    id: 'mob_013', categorie: 'mobila',
    titlu: 'Comodă cu sertare care nu se trag ușor',
    problema: 'Sertarele comodei se trag greu, se blochează sau scârțâie puternic.',
    cuvinte_cheie: ['comoda', 'sertar', 'greu', 'blocheaza', 'scartiie', 'lubrifiere', 'sina', 'ghidaj'],
    cauze_posibile: ['Ghidaje murdare de praf și umiditate', 'Lemn umflat din umiditate sau desen eronat'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '15-20 min',
      pasi: ['Extrage sertarele și curăță cu cârpă umedă ghidajele', 'Lasă să se usuce complet', 'Aplică ceară de lumânare sau spray silicon pe ghidaje', 'Testează reinserând sertarul'],
      sfat_pro: 'Ceroană de lumânare pe ghidaje de lemn — metoda bunicii care funcționează perfect.',
    },
    materiale_necesare: ['Ceară lumânare', 'Spray silicon', 'Cârpă'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_014', categorie: 'mobila',
    titlu: 'Pat sau comodă cu șuruburi slăbite',
    problema: 'Mobila s-a desfăcut parțial, îmbinările fac zgomot sau piesele se mișcă.',
    cuvinte_cheie: ['pat', 'comoda', 'suruburi', 'slabite', 'imbinare', 'strang', 'consolidare', 'confirmate'],
    cauze_posibile: ['Confirmații (șuruburi de mobilă) slăbite din utilizare repetată', 'Gauri lărgite în PAL'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-30 min',
      pasi: ['Strânge toate confirmațiile cu cheia hex corespunzătoare', 'Identifică găurile lărgite (confirmatul se rotește liber)', 'Introduce dopuri de lemn cu adeziv în gaura lărgită', 'Lasă 2h și reintroduce confirmatul'],
      sfat_pro: 'Strânge toate confirmațiile la fiecare 2-3 ani preventiv — 10 minute care previn dezasamblarea.',
    },
    materiale_necesare: ['Cheie hex', 'Dopuri lemn', 'Adeziv PVA'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'mob_015', categorie: 'mobila',
    titlu: 'Oglindă sau poliță de perete căzută',
    problema: 'Oglinda sau raftul de perete a căzut, dibluurile au ieșit din perete.',
    cuvinte_cheie: ['oglinda', 'raft', 'perete', 'dibluri', 'prindere', 'cazut', 'remontare', 'ancorare'],
    cauze_posibile: ['Dibluri nepotrivite pentru tipul de perete', 'Dibluri montate în glet sau tencuială slabă'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '20-30 min',
      pasi: ['Identifică tipul peretelui: BCA (moale), cărămidă (tare), gips-carton (special)', 'Alege diblul corespunzător greutății obiectului', 'Găurește cu bormașina la diametrul recomandat de diblu', 'Montează diblul, șurubul și agăță'],
      sfat_pro: 'Dibluri pentru gips-carton = tip fluture sau Molly. Niciodată dibluri normale în gips-carton!',
    },
    materiale_necesare: ['Dibluri potrivite', 'Șuruburi inox', 'Bormașină'],
    cand_chemi_specialistul: 'Nu e necesar. Verifică greutatea obiectului față de tipul de dibluri.',
    embedding: [],
  },

  // ── GRĂDINĂ ─────────────────────────────────────────────────────────────────

  {
    id: 'gra_001', categorie: 'gradina',
    titlu: 'Gazon uscat și îngălbenit',
    problema: 'Iarba din grădină s-a uscat, a îngălbenit sau are pete maronii.',
    cuvinte_cheie: ['gazon', 'uscat', 'galben', 'iarba', 'udare', 'fertilizare', 'aerare', 'sol'],
    cauze_posibile: ['Deficit de udare în perioadele calde', 'Lipsă azot în sol', 'Sol compactat care nu permite absorbția'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: 'Câteva săptămâni tratament',
      pasi: ['Udă profund de 2-3 ori pe săptămână dimineața (20-30min/zonă)', 'Fertilizează cu îngrășământ bogat în azot primăvara', 'Aerează solul cu aeratorul manual dacă e compactat', 'Resemănează zonele goale cu semințe de gazon'],
      sfat_pro: 'Udatul dimineața reduce evaporarea cu 70% față de udatul la prânz.',
    },
    materiale_necesare: ['Îngrășământ gazon cu azot', 'Aerator sol'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_002', categorie: 'gradina',
    titlu: 'Sistem de irigații înfundat sau cu presiune slabă',
    problema: 'Aspersoarele nu funcționează corect, unele zone nu se udă, presiunea e slabă.',
    cuvinte_cheie: ['irigatie', 'aspersor', 'infundat', 'presiune', 'furtun', 'filtru', 'picurare'],
    cauze_posibile: ['Filtre înfundate cu sedimente', 'Duze calcurate sau înfundate', 'Furtun îndoit sau perforat'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '1-2 ore',
      pasi: ['Verifică și curăță filtrul de la intrarea sistemului', 'Demontează duzele aspersoarelor și curăță orificiile', 'Inspectează furtunul principal pentru deformări sau perforații', 'Testează fiecare zonă individual'],
      sfat_pro: 'Curăță filtrele la începutul fiecărui sezon de irigare — 10 minute care previn problemele.',
    },
    materiale_necesare: ['Filtru irigație', 'Duze aspersor', 'Bandă teflon'],
    cand_chemi_specialistul: 'Nu e necesar pentru sisteme simple.',
    embedding: [],
  },
  {
    id: 'gra_003', categorie: 'gradina',
    titlu: 'Gard din lemn deteriorat sau putrezit',
    problema: 'Gardul din lemn are scânduri putrezite, crăpate sau vopseaua s-a cojit.',
    cuvinte_cheie: ['gard', 'lemn', 'putrezit', 'crapaturi', 'vopsea', 'tratament', 'inlocuire', 'impregnare'],
    cauze_posibile: ['Lemn netratat expus la intemperii', 'Vopsea/lazură depășită și deteriorată'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '4-8 ore',
      pasi: ['Înlocuiește scândurile putrezite complet (nu jumătăți)', 'Șlefuiește scândurile existente pentru a îndepărta vopseaua veche', 'Aplică impregnant de lemn exterior ca strat de bază', 'Finisează cu lazură sau vopsea pentru exterior (2 straturi)'],
      sfat_pro: 'Tratează lemnul nou înainte de montaj și pe toate fețele, inclusiv capetele — acolo putrezesc primul.',
    },
    materiale_necesare: ['Impregnant lemn', 'Lazură exterior', 'Scânduri înlocuitor'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_004', categorie: 'gradina',
    titlu: 'Pompă de grădină nu pornește sau debit slab',
    problema: 'Pompa de grădină nu pornește, face zgomot dar nu pompează sau debitul e mic.',
    cuvinte_cheie: ['pompa', 'gradina', 'porneste', 'debit', 'slab', 'impeller', 'filtru', 'amorsare'],
    cauze_posibile: ['Pompa neamorsată (fără apă în corp)', 'Filtru de aspirație înfundat cu nămol', 'Condensator de pornire defect'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '30-60 min',
      pasi: ['Umple pompa cu apă prin orificiul de amorsa înainte de pornire', 'Curăță filtrul de aspirație de nisip și mizerie', 'Testează condensatorul (se simte când pornești — dacă nu porneste singur, e defect)', 'Înlocuiește condensatorul dacă e necesar'],
      sfat_pro: 'Niciodată nu porni pompa fără apă — se arde în câteva secunde.',
    },
    materiale_necesare: ['Condensator pompă', 'Garnituri', 'Filtru aspirație'],
    cand_chemi_specialistul: 'Dacă motorul pompei e ars — service electrician.',
    embedding: [],
  },
  {
    id: 'gra_005', categorie: 'gradina',
    titlu: 'Roșii cu boli sau pete pe frunze',
    problema: 'Frunzele de roșii au pete galbene, maronii sau negre, plantele se ofilesc.',
    cuvinte_cheie: ['rosii', 'boli', 'pete', 'frunze', 'mana', 'alternaria', 'fungicid', 'tratament'],
    cauze_posibile: ['Mana roșiilor (Phytophthora infestans) — pete maronii pe frunze și tulpini', 'Alternaria — pete negre concentrice pe frunze inferioare'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '1-2 ore',
      pasi: ['Îndepărtează și arde frunzele afectate', 'Aplică zeamă bordeleză (1%) sau fungicid cu cupru', 'Repetă tratamentul la 7-10 zile sau după ploaie', 'Evită udatul pe frunze — uda la baza plantei'],
      sfat_pro: 'Tratamentul preventiv cu zeamă bordeleză de la începutul sezonului reduce riscul cu 80%.',
    },
    materiale_necesare: ['Zeamă bordeleză', 'Fungicid sistemic', 'Pulverizator'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_006', categorie: 'gradina',
    titlu: 'Copac sau arbust cu ramuri uscate',
    problema: 'Ramurile unui copac s-au uscat, au scoarță crăpată sau nu mai au frunze primăvara.',
    cuvinte_cheie: ['copac', 'arbust', 'ramuri', 'uscate', 'taiere', 'toaletare', 'boala', 'fungicid'],
    cauze_posibile: ['Boală fungică sau bacteriană', 'Leziuni de îngheț din iarna precedentă'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '1-4 ore',
      pasi: ['Taie ramurile uscate până dai de lemn verde (viu)', 'Dezinfectează uneltele cu alcool între tăieri pentru a nu răspândi boala', 'Aplică mastic de altoire pe tăieturile mari', 'Tratează copacul cu fungicid sistemic dacă e boală fungică'],
      sfat_pro: 'Uneltele de tăiat dezinfectate sunt esențiale — boala se transmite direct prin tăieturi.',
    },
    materiale_necesare: ['Ferăstrău copaci', 'Mastic altoire', 'Dezinfectant tăieturi'],
    cand_chemi_specialistul: 'Copaci mari lângă clădiri sau linii electrice — arborist certificat.',
    embedding: [],
  },
  {
    id: 'gra_007', categorie: 'gradina',
    titlu: 'Sol compactat — plantele cresc greu',
    problema: 'Solul e tare ca betonul, apa nu se absoarbe și plantele nu cresc bine.',
    cuvinte_cheie: ['sol', 'compactat', 'tare', 'aerare', 'afanare', 'compost', 'structura', 'nisip'],
    cauze_posibile: ['Trafic pietonal excesiv pe sol', 'Lipsă materie organică în sol argilos'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: '2-4 ore',
      pasi: ['Aerează cu aeratorul manual sau forca la 15-20cm adâncime', 'Incorporează compost matur în proporție de 20-30%', 'Adaugă nisip grosier dacă solul e argilos', 'Acoperă cu mulci organic pentru a preveni recompactarea'],
      sfat_pro: 'Compostul e aurul grădinarului — îmbunătățește orice tip de sol, de la argilos la nisipos.',
    },
    materiale_necesare: ['Forcă', 'Compost', 'Nisip grosier', 'Mulci organic'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_008', categorie: 'gradina',
    titlu: 'Dăunători pe plante — afide sau omizi',
    problema: 'Plantele au colonii de afide (păduchi de plante), omizi sau alte insecte dăunătoare.',
    cuvinte_cheie: ['afide', 'paduchi', 'omizi', 'daunatori', 'insecte', 'insecticid', 'tratament', 'bio'],
    cauze_posibile: ['Colonii de afide care se înmulțesc exponențial', 'Omizi din fluturi sau molii care depun ouă pe plante'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30-60 min',
      pasi: ['Tratament bio urgent: soluție 1L apă + 1 linguriță săpun de castilă pulverizat pe plante', 'Sau ulei de neem diluat (10ml/1L apă)', 'Tratament chimic: insecticid sistemic la indicațiile producătorului', 'Repetă la 5-7 zile până dispar'],
      sfat_pro: 'Buburuze, crisope și viespi parazite sunt aliații tăi naturali — nu le ucide cu insecticidele chimice.',
    },
    materiale_necesare: ['Ulei neem', 'Săpun insecticid', 'Pulverizator'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_009', categorie: 'gradina',
    titlu: 'Gard viu sau tufe care se usucă parțial',
    problema: 'Tuia, leandrul sau gardul viu are zone brune, uscate sau frunzele cad anormal.',
    cuvinte_cheie: ['gard', 'viu', 'tuia', 'usuca', 'brun', 'ciuperci', 'fungicid', 'phytophthora'],
    cauze_posibile: ['Excesul de apă — rădăcinile stau în apă (Phytophthora)', 'Deficit de nutrienți sau expunere greșită'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '1-2 ore',
      pasi: ['Verifică drenajul — dacă solul e mereu umed, faci drenaj sau reduci udarea', 'Taie ramurile complet uscate cu foarfeca dezinfectată', 'Aplică fungicid sistemic pentru tratament Phytophthora', 'Fertilizează cu îngrășământ special conifere/arbuști'],
      sfat_pro: 'Tuia tolerează seceta mult mai bine decât excesul de apă — mai puțin e mai mult.',
    },
    materiale_necesare: ['Fungicid sistemic', 'Îngrășământ special conifere'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_010', categorie: 'gradina',
    titlu: 'Furtun de grădină spart sau cu scurgeri',
    problema: 'Furtunul de grădină are fisuri, bășici sau se scurge la fitinguri.',
    cuvinte_cheie: ['furtun', 'gradina', 'spart', 'scurgere', 'reparatie', 'fiting', 'conector', 'cuplaj'],
    cauze_posibile: ['Fisuri din îngheț sau UV', 'Garnitură uzată la racorduri'],
    solutie: {
      dificultate: 'Foarte ușor', timp_estimat: '10-15 min',
      pasi: ['Localizează exact fisura sau scurgerea', 'Fisuri mici: bandă de reparații furtun autovulcanizantă', 'Fisuri mari sau perforații: taie zona afectată și reconectează cu un conector rapid', 'Garnitură uzată la racord: înlocuiește garnitura de cauciuc'],
      sfat_pro: 'Un set de conectori rapizi pentru furtun (30 RON) îți permite repararea oricărei zone în 2 minute.',
    },
    materiale_necesare: ['Conector reparații furtun', 'Bandă reparații furtun', 'Garnitură racord'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_011', categorie: 'gradina',
    titlu: 'Compostare incorectă — miros urât',
    problema: 'Compostul miroase urât (ouă clocite), e prea umed sau nu se descompune corect.',
    cuvinte_cheie: ['compost', 'miros', 'urat', 'umed', 'descompunere', 'brun', 'verde', 'aerare'],
    cauze_posibile: ['Dezechilibru între materiale verzi (azot) și brune (carbon)', 'Lipsă oxigen din compactare sau umiditate excesivă'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30 min',
      pasi: ['Adaugă materiale brune (paie, carton, frunze uscate) în proporție egală cu verdele', 'Aerează amestecul cu forca în interior', 'Dacă e prea umed: adaugă paie sau hârtie de ziar', 'Acoperă pentru a controla umiditatea'],
      sfat_pro: 'Regula de aur: ½ materiale verzi + ½ materiale brune. Compostul bun miroase a pădure, nu a putrefacție.',
    },
    materiale_necesare: ['Paie', 'Carton', 'Furcă compost'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_012', categorie: 'gradina',
    titlu: 'Flori de grădină care se ofilesc rapid',
    problema: 'Florile plantate în grădină sau ghivece se ofilesc rapid deși le uzi.',
    cuvinte_cheie: ['flori', 'ofilesc', 'ghiveci', 'udare', 'drenaj', 'radacini', 'sol', 'arsuri', 'soare'],
    cauze_posibile: ['Exces de apă — rădăcinile putrezesc', 'Arsuri solare din expunere directă la prânz', 'Sol fără nutrienți sau pH necorespunzător'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30 min',
      pasi: ['Verifică dacă solul e umed la 5cm adâncime — dacă da, NU uda', 'Verifică drenajul ghiveciului (găuri la bază)', 'Mută florile sensibile la umbră parțială la prânz', 'Fertilizează cu îngrășământ lichid la 2 săptămâni'],
      sfat_pro: 'Regula degetului: bagă degetul 2cm în pământ. Dacă e uscat — uda. Dacă e umed — nu uda.',
    },
    materiale_necesare: ['Sol cu drenaj bun', 'Îngrășământ lichid'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_013', categorie: 'gradina',
    titlu: 'Mici rozătoare în grădină — cârtițe sau șoareci',
    problema: 'Apar movile de pământ sau galerii sub gazon, plantele dispar din pământ.',
    cuvinte_cheie: ['cartita', 'soarece', 'rozatoare', 'galerie', 'movile', 'capcana', 'alungare'],
    cauze_posibile: ['Cârtițe în căutare de râme (movile de pământ)', 'Șoareci de câmp care consumă rădăcini și bulbi'],
    solutie: {
      dificultate: 'Mediu', timp_estimat: 'Câteva zile tratament',
      pasi: ['Identifică animalul: cârtița = movile, șoarecele = galerii la nivelul solului', 'Capcane mecanice specifice (umane sau letale) plasate la intrarea galeriei', 'Turații cu vibrații în sol (eoliene) — cârtițele le evită', 'Plante respingătoare: molid, mentă sălbatică la margini'],
      sfat_pro: 'Cârtițele nu mănâncă plante — mănâncă râme. Pot fi benefice dacă nu deranjează.',
    },
    materiale_necesare: ['Capcane cârtițe', 'Turbine sol', 'Plante respingătoare'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_014', categorie: 'gradina',
    titlu: 'Iarbă cu buruieni invazive',
    problema: 'Gazonul e invadat de buruieni, pir, susai sau mătăciune care se răspândesc rapid.',
    cuvinte_cheie: ['buruieni', 'gazon', 'pir', 'mataciuna', 'erbicid', 'plivire', 'invazie', 'control'],
    cauze_posibile: ['Goluri în gazon ocupate de buruieni', 'Semințe aduse de vânt sau animale'],
    solutie: {
      dificultate: 'Ușor-Mediu', timp_estimat: '1-4 ore',
      pasi: ['Plivire manuală pentru zone mici — smulge cu rădăcini cu tot', 'Erbicid selectiv pentru gazon (nu omoară iarba) pentru suprafețe mari', 'Resemânează zonele goale după eliminare', 'Tunde regulat — buruienile cresc mai repede decât iarba'],
      sfat_pro: 'Plivitul după ploaie e de 3× mai ușor — rădăcinile ies întregi din sol moale.',
    },
    materiale_necesare: ['Erbicid selectiv gazon', 'Greblă rădăcini', 'Sapă'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
  {
    id: 'gra_015', categorie: 'gradina',
    titlu: 'Plantație de legume atacată de boli fungice',
    problema: 'Mana sau alte boli fungice atacă castraveții, cartofii sau ardeii.',
    cuvinte_cheie: ['legume', 'mana', 'fungus', 'ciuperca', 'castraveti', 'cartofi', 'ardei', 'tratament', 'preventiv'],
    cauze_posibile: ['Mana (Peronospora) favorizată de umiditate ridicată și temperaturi moderate', 'Transmitere prin sol sau unelte contaminate'],
    solutie: {
      dificultate: 'Ușor', timp_estimat: '30-60 min',
      pasi: ['Aplică preventiv zeamă bordeleză 1% la 10-14 zile de la răsărit', 'Evită udatul pe frunze — uda la baza plantelor', 'Îndepărtează și arde frunzele afectate', 'Rotește culturile anual — nu planta legume din aceeași familie în același loc'],
      sfat_pro: 'Rotația culturilor reduce riscul de boli fungice cu 60%. Niciodată roșii după roșii.',
    },
    materiale_necesare: ['Zeamă bordeleză', 'Fungicid Ridomil', 'Pulverizator'],
    cand_chemi_specialistul: 'Nu e necesar.',
    embedding: [],
  },
];
